(function(){var g={}; var _ = _ || {}
var f=function(window){var wP=function(){this.B=[0,1,2,4,8,16,32,64,128,27,54];this.C=[new Uint32Array(256),new Uint32Array(256),new Uint32Array(256),new Uint32Array(256)];this.l=[new Uint32Array(256),new Uint32Array(256),new Uint32Array(256),new Uint32Array(256)];this.A=new Uint32Array(256);this.o=new Uint32Array(256);this.w=new Uint32Array(0);this.h=this.a=this.j=this.f=null;var a=this.A,b=this.o,c=this.C,d=c[0],e=c[1],f=c[2];c=c[3];var g=this.l,h=g[0],l=g[1],m=g[2];g=g[3];var n=new Uint32Array(256),p=0,q=0,t;for(t=0;256>
t;t++)n[t]=128>t?t<<1:t<<1^283;for(t=0;256>t;t++){var v=q^q<<1^q<<2^q<<3^q<<4;v=v>>>8^v&255^99;a[p]=v;b[v]=p;var z=n[p],D=n[z],G=n[D],F=257*n[v]^16843008*v;d[p]=F<<24|F>>>8;e[p]=F<<16|F>>>16;f[p]=F<<8|F>>>24;c[p]=F;F=16843009*G^65537*D^257*z^16843008*p;h[v]=F<<24|F>>>8;l[v]=F<<16|F>>>16;m[v]=F<<8|F>>>24;g[v]=F;p?(p=z^n[n[n[G^z]]],q^=n[n[q]]):p=q=1}},xP=function(a){a=_.aj(a);for(var b=new Uint32Array(4),c=0;4>c;c++)b[c]=a.getUint32(4*c);return b},yP=function(){this.a=null},zP=function(){this.j={};
this.l=!1;this.g=new _.K("clpp.crypto")},BP=function(a,b){return function(c){var d,e,f;return _.E(function(g){if(1==g.a){d=c.request||null;if(!(d&&2===d.type&&d.keyInfo&&c.data))return g.F(2);e=d.uris[0];a.g.debug("Decrypting AES-128-encrypted video segment",e);f=c;return _.x(g,AP(a,b,c.data,d.keyInfo,e),3)}2!=g.a&&(f.data=g.f);return g["return"](c)})}},CP=function(a,b,c){var d,e,f,g,h,l;return _.E(function(m){if(1==m.a){d=_.rj(c);if(e=(new _.qi(c)).Pa.endsWith(".drmtoday.com"))f=b.getConfiguration(),
_.Om(d,f);g=c+JSON.stringify(d.headers);if(a.j[g])return m["return"](a.j[g]);_.A(m,2);return _.x(m,b.getNetworkEngine().fetch(d).O,4)}if(2!=m.a)return h=m.f,a.j[g]=h.data,m["return"](h.data);l=_.C(m);e&&1001===l.code&&412===l.data.status&&a.g.warn("Wrong DRMtoday credentials, server responded with 412.");throw l;})},AP=function(a,b,c,d,e){var f,g,h,l,m;return _.E(function(n){switch(n.a){case 1:return f=new ArrayBuffer(0),_.A(n,2),_.x(n,CP(a,b,d.url),4);case 4:f=n.f;_.ah(n,3);break;case 2:return g=
_.C(n),a.g.warn("Could not fetch AES key",g),b.onError(new _.P(1,7,7104,null,g)),n["return"](c);case 3:return _.A(n,5),h=a.l?new yP:new wP,_.x(n,h.importKey(f),7);case 7:return _.x(n,h.decrypt(c,d.iv),8);case 8:return l=n.f,n["return"](l);case 5:return m=_.C(n),a.g.warn("Could not decrypt segment data!",e,m),b.onError(new _.P(1,3,3103,null,m)),n["return"](c)}})};
wP.prototype.importKey=function(a){a=xP(a);for(var b=!0,c=0;c<a.length&&b;)b=a[c]===this.w[c],c++;if(b)return new Promise(function(n){return n()});this.w=a;this.a=a.length;if(4!==this.a&&6!==this.a&&8!==this.a)throw Error("Invalid aes key size\x3d"+this.a);this.h=4*(this.a+7);this.f=new Uint32Array(this.h);this.j=new Uint32Array(this.h);b=this.A;var d=this.B;var e=this.l;c=e[0];var f=e[1],g=e[2],h=e[3],l=0,m=0;for(e=0;e<this.h;e++)e<this.a?l=this.f[e]=a[e]:(m=l,0===e%this.a?(m=m<<8|m>>>24,m=b[m>>>
24]<<24|b[m>>>16&255]<<16|b[m>>>8&255]<<8|b[m&255],m^=d[e/this.a|0]<<24):6<this.a&&4===e%this.a&&(m=b[m>>>24]<<24|b[m>>>16&255]<<16|b[m>>>8&255]<<8|b[m&255]),l=(this.f[e-this.a]^m)>>>0,this.f[e]=l);for(a=0;a<this.h;a++)e=this.h-a,m=a&3?this.f[e]:this.f[e-4],this.j[a]=4>a||4>=e?m:c[b[m>>>24]]^f[b[m>>>16&255]]^g[b[m>>>8&255]]^h[b[m&255]],this.j[a]>>>=0;return new Promise(function(n){return n()})};
wP.prototype.decrypt=function(a,b){var c=0,d=this.a+6,e=this.j,f=this.o,g=this.l,h=g[0],l=g[1],m=g[2];g=g[3];var n=xP(b),p=n[0],q=n[1],t=n[2];n=n[3];for(var v=_.$i(a),z=new Int32Array(v.length),D,G,F,B,I,O,M,ba,ha,qa,Ta,Fa,Ca,na=this.G.bind(this);c<v.length;){ba=na(v[c]);ha=na(v[c+1]);qa=na(v[c+2]);Ta=na(v[c+3]);I=ba^e[0];O=Ta^e[1];M=qa^e[2];B=ha^e[3];Fa=4;for(Ca=1;Ca<d;Ca++)D=h[I>>>24]^l[O>>16&255]^m[M>>8&255]^g[B&255]^e[Fa],G=h[O>>>24]^l[M>>16&255]^m[B>>8&255]^g[I&255]^e[Fa+1],F=h[M>>>24]^l[B>>
16&255]^m[I>>8&255]^g[O&255]^e[Fa+2],B=h[B>>>24]^l[I>>16&255]^m[O>>8&255]^g[M&255]^e[Fa+3],I=D,O=G,M=F,Fa+=4;D=f[I>>>24]<<24^f[O>>16&255]<<16^f[M>>8&255]<<8^f[B&255]^e[Fa];G=f[O>>>24]<<24^f[M>>16&255]<<16^f[B>>8&255]<<8^f[I&255]^e[Fa+1];F=f[M>>>24]<<24^f[B>>16&255]<<16^f[I>>8&255]<<8^f[O&255]^e[Fa+2];B=f[B>>>24]<<24^f[I>>16&255]<<16^f[O>>8&255]<<8^f[M&255]^e[Fa+3];Fa+=3;z[c]=na(D^p);z[c+1]=na(B^q);z[c+2]=na(F^t);z[c+3]=na(G^n);p=ba;q=ha;t=qa;n=Ta;c+=4}return new Promise(function(Ia){var tb=z.buffer;
var Jb=tb.byteLength,Lc=Jb&&(new DataView(tb)).getUint8(Jb-1);tb=Lc?tb.slice(0,Jb-Lc):tb;Ia(tb)})};wP.prototype.destroy=function(){this.B=this.j=this.f=this.l=this.C=this.o=this.A=this.h=this.a=this.w=null;return new Promise(function(a){return a()})};wP.prototype.G=function(a){return a<<24|(a&65280)<<8|(a&16711680)>>8|a>>>24};yP.prototype.importKey=function(a){var b=this,c;return _.E(function(d){if(1==d.a)return c=b,_.x(d,crypto.subtle.importKey("raw",a,{name:"AES-CBC"},!1,["decrypt"]),2);c.a=d.f;_.y(d)})};yP.prototype.decrypt=function(a,b){var c=this,d;return _.E(function(e){if(1==e.a)return _.x(e,crypto.subtle.decrypt({name:"AES-CBC",iv:b},c.a,a),2);d=e.f;return e["return"](d)})};yP.prototype.destroy=function(){this.a=null;return new Promise(function(a){return a()})};_.w(zP,_.Ir);zP.prototype.f=function(){if(window.crypto&&crypto.subtle){var a=crypto.subtle.decrypt;a=typeof crypto.subtle.importKey===_.qe&&typeof a===_.qe}else a=!1;(this.l=a)||this.g.warn("No WebCrypto APIs found. Will fallback to software AES")};zP.prototype.o=function(a){var b=BP(this,a);a.getNetworkEngine().hd(b)};zP.prototype.a=function(){this.j={}};zP.prototype.id=function(){return"crypto"};_.H("clpp.crypto.CryptoComponent",zP);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();