(function(){var g={}; var _ = _ || {}
var f=function(window){var LN="CLPP Subtitle Styles",MN="Unsupported unit",NN="clpp-text-plain",ON="clpp-text-ttml",PN="clpp.htmlcue.HtmlTextDisplayer",QN="initial",RN=function(a){return _.Xh(a,{ug:function(b,c){return b.ta(c)}})},SN=function(a,b){if(0===b.length)return a;var c=a,d=a.findIndex(function(e){return e.startTime>=b[0].startTime});0<=d&&(c=c.slice(0,d));return c.concat(b)},TN=function(a,b){for(var c=0,d=a.length-1;c<=d;){var e=c+d>>1,f=b(a[e]);if(0===f)return e;0<f?c=e+1:d=e-1}return-1},UN=function(){},VN=function(a){if(!a.input)return null;
var b=a.input.match(/^([^<]*)(<[^>]+>?)?/);b=b[1]?b[1]:b[2];a.input=a.input.substr(b.length);return b},XN=function(a){for(var b=null;b=a.match(/&(amp|lt|gt|lrm|rlm|nbsp);/);)a=a.replace(b[0],function(c){return WN[c]});return a},ZN=function(a,b){YN(a,b);Array.from(b.getElementsByTagName("*")).forEach(function(c){YN(a,c)})},YN=function(a,b){for(var c in a)null!=a[c]&&(b.style[c]=a[c])},$N=function(a,b){return 0===a?"0":a+b},aO=function(a,b){return 1>Math.abs(a-b)||a<b},bO=function(a,b){return a<b&&
1<Math.abs(a-b)},cO=function(a,b){return a>b&&1<Math.abs(a-b)},dO=function(a,b){return 1>Math.abs(a-b)||a>b},eO=function(a,b,c,d,e,f){this.left=a;this.f=b;this.top=c;this.a=d;this.height=e;this.width=f},fO=function(a){return new eO(a.left,a.f,a.top,a.a,a.height,a.width)},gO=function(a){var b=a.getBoundingClientRect(),c=getComputedStyle(a,null),d=parseFloat(c.getPropertyValue("border-left-width"))||0,e=parseFloat(c.getPropertyValue("border-right-width"))||0,f=parseFloat(c.getPropertyValue("border-top-width"))||
0;c=parseFloat(c.getPropertyValue("border-bottom-width"))||0;var g=(b.top||a.offsetTop)+f;f=(b.height||a.offsetHeight)-f-c;return new eO(b.left+d,b.right+e,g,(b.bottom||g+f)+c,f,(b.width||a.offsetWidth)-d-e)},hO=function(a,b){return b.some(function(c){return bO(a.left,c.f)&&cO(a.f,c.left)&&bO(a.top,c.a)&&cO(a.a,c.top)})},iO=function(a,b){return dO(a.top,b.top)&&aO(a.a,b.a)&&dO(a.left,b.left)&&aO(a.f,b.f)},jO=function(a,b,c){switch(c){case "+x":return bO(a.left,b.left);case "-x":return cO(a.f,b.f);
case "+y":return bO(a.top,b.top);case "-y":return cO(a.a,b.a);default:throw Error("Unknown axis");}},kO=function(a,b,c){this.id=a;this.w=b;this.B=c;this.a=this.o();this.j=!1},lO=function(a,b,c){kO.call(this,a.id,"clpp-text-cue",{});this.l=b;this.f=a;this.h=!!this.f.backgroundImage;this.C=c},nO=function(a){var b=a.a.childNodes[0],c=a.a.getBoundingClientRect(),d=b.getClientRects();b=c.height/d.length;c=c.width/d.length;return mO(a)?b:c},qO=function(a,b,c){return mO(a)&&_.N.na(c)?$N(c,_.Df):(oO(a)||
pO(a))&&_.N.na(b)?$N(b,"%"):QN},oO=function(a){return a.f.writingMode===_.qg},pO=function(a){return a.f.writingMode===_.rg},mO=function(a){return a.f.writingMode===_.$h},rO=function(a,b,c){return(oO(a)||pO(a))&&_.N.na(c)?$N(c,_.Df):oO(a)&&_.N.R(c)?$N(0,_.Df):mO(a)&&_.N.na(b)?$N(b,"%"):QN},sO=function(a,b){if(typeof a.f.position===_.k&&typeof a.f.size===_.k)switch(b){case _.Ce:return a.f.position;case "auto":case _.sd:return a.f.position-a.f.size/2;case _.De:return a.f.position-a.f.size}return 0},
tO=function(a){switch(a.f.positionAlign){case _.Ce:return _.ye;case "auto":case _.sd:return _.Zh;case _.De:return _.Kf}return a.f.textAlign},uO=function(a){if(!a.f.positionAlign)switch(a.f.textAlign){case _.ye:case _.ye:return _.Ce;case _.Zh:return _.sd;case _.Kf:case _.Kf:return _.De}return a.f.positionAlign},vO=function(a){switch(a.f.writingMode){case _.$h:return"horizontal-tb";case _.qg:return _.qg;case _.rg:return _.rg;default:throw Error("Unknown writing mode");}},wO=function(a,b){this.l=a;this.f=
a.a;this.j=void 0===b?!1:b;this.a=gO(a.a);this.h=[]},xO=function(a,b){if(a.j)switch(b.writingMode){case _.$h:return["-y"];case _.qg:return["+x"];case _.rg:return["-x"]}var c=[];switch(b.writingMode){case _.$h:c=["+y","-y"];break;case _.qg:c=["+x","-x"];break;case _.rg:c=["-x","+x"]}0>b.line&&(c=c.reverse());return c},yO=function(a){for(a.h=[];0<a.f.childNodes.length;)a.f.removeChild(a.f.childNodes[0]);a.a=gO(a.l.a)},zO=function(a,b,c){kO.call(this,a,b,c);this.h=null;this.l=[]},AO=function(a,b){yO(a.h);
a.l.unshift(b);for(var c=_.u(a.l),d=c.next();!d.done;d=c.next())a.h.append(d.value)},BO=function(a,b){zO.call(this,a.id,"clpp-text-cue-region",b);this.f=a},CO=function(a,b,c){a=a.f;var d=a.viewportAnchorUnits;if(d===_.ei)return a.viewportAnchorY/100*c-a.regionAnchorY/100*b;if(0===d)return a.viewportAnchorY-a.regionAnchorY;throw Error(MN);},EO=function(a){this.g=new _.K("clpp.htmlcue.StyleManager");this.l=[];this.h=a.getSurface().getUniqueCssClass();this.j=[];this.a=DO(this,this.h);this.f=DO(this,
this.h,!0);this.f.disabled=!0;this.g.debug("Stylesheet CLPP Subtitle Styles has been created.")},FO=function(a,b){var c=!1;try{a.f.insertRule(b,0);var d=a.f.cssRules[0];d instanceof CSSStyleRule&&(c=d.selectorText.split(",").every(function(e){return 0===e.trim().indexOf("."+a.h+" ")}))}catch(e){}0<a.f.cssRules.length&&a.f.deleteRule(0);return c},GO=function(a,b){var c="."+a.h+" .clpp-text-container",d=c+" .clpp-text-cue";return b=b.replace(/::cue\((#[^)]+)\)/g,c+" $1").replace(/::cue\(([^)]+)\)/g,
d+" $1").replace(/::cue-region\(([^)]+)\)/g,c+" $1 .clpp-text-cue").replace(/::cue/g,d).replace(/::cue-region/g,c+" .clpp-text-cue-region .clpp-text-cue").replace(/::ttml/g,c)},DO=function(a,b,c){var d=document.createElement(_.Yf),e=d.dataset;e.name=LN;e["for"]=b;c&&(e.name="CLPP Subtitle Styles (sandbox)",e.sandbox=!0);b=document.head;b.appendChild(d);HO(a,b);a.g.debug("Created HTML style element #CLPP Subtitle Styles.");return d.sheet},HO=function(a,b){var c=new MutationObserver(function(d){d.forEach(function(e){e.removedNodes.forEach(function(f){f.id===
LN&&a.g.error("PRESTOplay HTML style element #CLPP Subtitle Styles has been unexpectedly removed! Some styles will not work!")})})});c.observe(b,{subtree:!1,childList:!0});a.l.push(function(){return c.disconnect()})},KO=function(a){_.ht.call(this,a);var b=this;this.g=new _.K(PN);this.m=a;this.M=IO(a);this.j=!1;this.f=[];this.C=a.getSurface().getContainer();this.h=new EO(a);this.a=new zO(null,"clpp-text-container",{});this.w=new _.ys(a.getSurface(),this.Vi.bind(this));this.J=null;this.C?(this.C.appendChild(this.a.a),
this.a.init(null)):this.g.warn("No container element! Subtitles will not appear. Please check your player surface configuration or switch to NativeTextDisplayer.");this.G=new _.uk(function(){JO(b)});this.A=new Map;this.l=null},IO=function(a){a=_.N.Oa(a.getConfiguration().htmlcue||{});_.N.R(a.stretchSmpteImage)&&(a.stretchSmpteImage=!1);_.N.R(a.enableResizeObserver)&&(a.enableResizeObserver=!0);return a},LO=function(a,b){return a.startTime<=b&&a.endTime>b},JO=function(a,b){if((b||a.j)&&a.C){var c=
a.m.getPosition();if(b||a.J!==c&&a.m.getState()===_.Vo){a.J=c;var d=MO(a,c);(c=b)||(c=a.l,c=!(null===c&&null===d||null!==c&&null!==d&&c.start===d.start&&c.end===d.end));if(c&&(a.l=d,NO(a),d)){c={color:a.getFontColor()||void 0,backgroundColor:a.getBackgroundColor()||void 0,fontFamily:a.getFontFamily()||void 0,textShadow:_.mt(a)||void 0};d=a.f.slice(d.start,d.end+1);d=_.u(d);for(var e=d.next();!e.done;e=d.next()){var f=a;e=e.value;var g=f.a.a,h=null;switch(e.payloadType){case _.zg:h="clpp-text-vtt";
break;case _.gg:h=ON;break;case _.Yh:h=NN}h&&!g.classList.contains(h)&&_.rp(g,h);g=gO(f.a.a);if(0===g.width||0===g.height)f.g.warn("The height or width of the `.clpp-text-container` element is zero. Captions will not be displayed. Please check if the `clpp.styles.css` file has been included.");else{YN({fontSize:OO(f,e.containerRows)},f.a.a);g=null;h=e.payloadType===_.zg;var l=e.payloadType===_.gg;e.region&&(h||l||e.backgroundImage)&&(f.A.has(e.region.id)?g=f.A.get(e.region.id):(g=new BO(e.region,
{}),f.A.set(e.region.id,g),AO(f.a,g)));e=new lO(e,f.M,c);g?AO(g,e):AO(f.a,e)}}}}}},MO=function(a,b){var c=TN(a.f,function(e){return LO(e,b)?0:b!==e.startTime?b-e.startTime:b-e.endTime});if(-1===c)return null;for(var d=c;0<=d-1&&LO(a.f[d-1],b);)d--;for(;c+1<a.f.length&&LO(a.f[c+1],b);)c++;return{start:d,end:c}},PO=function(a){NO(a);a.J=null;a.l=null;a.f=[]},NO=function(a){a.A.clear();if(a.a){var b=a.a.a;b.classList.remove("clpp-text-vtt");b.classList.remove(ON);b.classList.remove(NN);a=a.a;yO(a.h);
a.l=[]}},OO=function(a,b){var c=gO(a.a.a).height;if(null!==a.I)return a.getFontSize();if(null!==a.B){var d=a.getFontSizePercent();return Math.round(c*d)+_.Df}if(typeof b===_.k&&0<b)return Math.round(c/b)+_.Df;d=a.getFontSizePercent();return Math.round(c*d)+_.Df},QO=function(){},RO=function(){};
UN.prototype.parse=function(a){a={input:a};for(var b=_.tp(_.Yd),c=[],d=b,e;null!==(e=VN(a));)if("\x3c"===e[0])if("/"===e[1])c.length&&c[c.length-1]===e.substr(2).replace("\x3e","")&&(c.pop(),d=d.parentNode);else{if(e=e.match(/^<([^.\s/0-9>]+)(\.[^\s\\>]+)?([^>\\]+)?(\\?)>?$/)){var f=e[1];var g=e[3];var h=SO[f];h?(h=_.tp(h),(f=TO[f])&&g&&h.setAttribute(f,g.trim()),g=h):g=null;!g||UO[g.localName]&&UO[g.localName]!==d.localName||(e[2]&&(g.className=e[2].substr(1).replace(/\./g," ")),c.push(e[1]),d.appendChild(g),
d=g)}}else d.appendChild(document.createTextNode(XN(e)));return b};var SO={c:"c",i:"i",b:"b",u:"u",ruby:"ruby",rt:"rt",v:"v",lang:"lang"},TO={v:"voice",lang:"lang"},UO={rt:"ruby"},WN={"\x26amp;":"\x26","\x26lt;":"\x3c","\x26gt;":"\x3e","\x26lrm;":"\u200e","\x26rlm;":"\u200f","\x26nbsp;":"\u00a0"};kO.prototype.init=function(){this.j=!0};kO.prototype.A=function(){return!1};_.w(lO,kO);lO.prototype.A=function(){return!this.h&&!(this.f.region&&this.f.region.displayAlign)};
lO.prototype.init=function(a){kO.prototype.init.call(this,a);if(this.h)_.rp(this.a,"clpp-text-cue-image"),this.a.style.backgroundImage='url("'+this.f.backgroundImage+'")',this.l.stretchSmpteImage&&(this.a.style.backgroundSize="contain");else if(a){var b=this.f;if(b.payloadType===_.gg){var c=_.tp(_.Yd);c.innerHTML=b.payload;b=c}else b.payloadType===_.zg?b=(new UN).parse(b.payload):(c=_.tp(_.Yd),c.textContent=b.payload,b=c);_.rp(b,this.w);this.id&&(b.id=this.id);c=_.u(this.f.cssClassList);for(var d=
c.next();!d.done;d=c.next())_.rp(b,d.value);YN({writingMode:vO(this)},b);this.a.appendChild(b);_.rp(this.a,"clpp-text-wrapper");c=_.u(this.f.cssClassList);for(d=c.next();!d.done;d=c.next())_.rp(this.a,"clpp-text-wrapper__"+d.value);_.N.R(this.f.line)&&(this.f.lineInterpretation=_.ai,this.f.line=mO(this)?-1:0);c=vO(this);YN({writingMode:c,webkitWritingMode:c,direction:QN,textAlign:tO(this)},this.a);if(!this.f.region||!this.f.region.displayAlign){c=sO(this,uO(this));d=rO(this,c,null);var e=qO(this,
c,null),f=pO(this)&&_.N.R(null)?$N(0,_.Df):QN;YN({position:"absolute",left:d,right:f,top:e,width:mO(this)?$N(this.f.size,"%"):QN,height:oO(this)||pO(this)?$N(this.f.size,"%"):QN},this.a);d=this.f;a=mO(this)?a.height:a.width;e=nO(this);if(d.lineInterpretation===_.ai)f=e*Math.round(d.line),Math.abs(f)>a&&(f=e*(0>d.line?0:-1)),0>f&&(f+=a);else{f=e/a*100;var g=d.line;switch(d.lineAlign){case _.sd:g-=f/2;break;case _.le:g-=f}f=Math.round(g/100*a)}pO(this)&&(f=a-f-e);a=f;d=rO(this,c,a);e=pO(this)&&_.N.R(a)?
$N(0,_.Df):QN;YN({left:d,right:e,top:qO(this,c,a)},this.a)}ZN(this.C,b)}};lO.prototype.o=function(){return _.tp(_.Yd)};wO.prototype.append=function(a){var b=a.a;b.style.visibility=_.se;this.f.appendChild(b);a.j||a.init(this.a);if(a.A()){a:{var c=gO(a.a);var d=xO(this,a.f),e=nO(a),f=fO(c),g=null,h=0;d=_.u(d);for(var l=d.next();!l.done;l=d.next()){for(l=l.value;jO(c,this.a,l)||iO(c,this.a)&&hO(c,this.h);){var m=c,n=e;switch(l){case "+x":m.left+=n;m.f+=n;break;case "-x":m.left-=n;m.f-=n;break;case "+y":m.top+=n;m.a+=n;break;case "-y":m.top-=n,m.a-=n}}if(this.j||iO(c,this.a))break a;l=this.a;l=Math.max(0,Math.min(c.f,
l.f)-Math.max(c.left,l.left))*Math.max(0,Math.min(c.a,l.a)-Math.max(c.top,l.top))/(c.height*c.width);l>h&&(g=fO(c),h=l);c=fO(f)}c=g||f}YN({top:$N(c.top-this.a.top,_.Df),bottom:$N(this.a.a-c.a,_.Df),left:$N(c.left-this.a.left,_.Df),right:$N(this.a.f-c.f,_.Df),height:$N(c.height,_.Df),width:$N(c.width,_.Df)},a.a)}b.style.visibility="visible";this.h.push(gO(a.a))};_.w(zO,kO);zO.prototype.init=function(){this.h=new wO(this);this.j=!0};zO.prototype.o=function(){var a=_.tp(_.Yd);_.rp(a,this.w);this.id&&(a.id=this.id);return a};_.w(BO,zO);
BO.prototype.init=function(a){a:{var b=this.f;switch(b.widthUnits){case 0:b=b.width;break a;case _.ei:b=b.width/100*a.width;break a;default:throw Error(MN);}}var c=this.f;var d=c.viewportAnchorUnits;if(d===_.ei)c=c.viewportAnchorX/100*a.width-c.regionAnchorX/100*b;else if(0===d)c=c.viewportAnchorX-c.regionAnchorX;else throw Error(MN);d=a.height;var e=CO(this,d,a.height);YN(this.B,this.a);YN({left:$N(c,_.Df),top:$N(e,_.Df),width:$N(b,_.Df),height:$N(d,_.Df)},this.a);this.f.writingMode&&YN({display:"flex",
"flex-direction":this.f.writingMode},this.a);this.f.displayAlign&&YN({"justify-content":this.f.displayAlign},this.a);b=_.u(this.f.cssClassList);for(c=b.next();!c.done;c=b.next())_.rp(this.a,c.value);a:switch(b=this.f,b.heightUnits){case 0:b=b.height;break a;case _.ei:b=b.height/100*a.height;break a;case 2:b=b.height;d=new lO(new _.di(0,1,"Lorem ipsum",_.Yh),{},{});c=d.a;this.a.appendChild(c);d.init(gO(this.a));d=c.getBoundingClientRect().height;this.a.removeChild(c);b*=d;break a;default:throw Error(MN);
}a=CO(this,b,a.height);YN({top:$N(a,_.Df),height:$N(b,_.Df)},this.a);this.h=new wO(this,!0);this.j=!0};BO.prototype.getId=function(){return this.f.id};EO.prototype.appendRule=function(a){if(null!=this.a&&!this.j.some(function(c){return c===a})){var b=GO(this,a);if(FO(this,b)){try{this.a.insertRule(b,this.a.cssRules.length),this.g.debug("Added CSS rule "+b)}catch(c){this.g.error("An error occurred when adding a CSS rule: "+b)}this.j.push(a)}else this.g.warn("Stylesheet CLPP Subtitle Styles ignoring the CSS rule because it's not safe: "+b)}};
EO.prototype.destroy=function(){var a=this;return _.E(function(b){if(null==a.a)return b["return"]();a.l.forEach(function(c){return c()});a.l=[];if(null!=a.a){for(;0<a.a.cssRules.length;)a.a.deleteRule(0);a.j=[]}document.head.removeChild(a.a.ownerNode);document.head.removeChild(a.f.ownerNode);a.a=null;a.f=null;a.g.debug("Stylesheet CLPP Subtitle Styles has been destroyed.");_.y(b)})};_.w(KO,_.ht);_.r=KO.prototype;_.r.append=function(a,b){if(null!=this.h&&0!==a.length){for(var c=_.u(b),d=c.next();!d.done;d=c.next())this.h.appendRule(d.value);a.sort(function(e,f){return e.startTime!==f.startTime?e.startTime-f.startTime:e.endTime-f.endTime});this.f=SN(this.f,RN(a));this.l=null;JO(this,!1)}};_.r.ub=function(){null==this.h||JO(this,!0)};
_.r.destroy=function(){var a=this;return _.E(function(b){if(1==b.a){if(null==a.h)return b["return"]();PO(a);a.G.stop();return _.x(b,a.h.destroy(),2)}a.h=null;a.C.removeChild(a.a.a);a.a=null;a.w.stop();a.w=null;a.j=!1;_.y(b)})};_.r.remove=function(a,b){if(null==this.h)return!1;this.f=this.f.filter(function(c){return c.startTime<a||c.endTime>=b});this.l=null;JO(this,!0);return!0};_.r.isTextVisible=function(){return this.j};
_.r.setTextVisibility=function(a){null!=this.h&&this.j!==a&&((this.j=a)?(this.G.jb(.25),this.M.enableResizeObserver&&this.w.start(),JO(this,!0)):(this.G.stop(),this.w.stop(),PO(this)))};_.r.zd=function(){return this.f};_.r.Vi=function(){JO(this,!0)};_.H(PN,KO);KO.prototype.setTextVisibility=KO.prototype.setTextVisibility;KO.prototype.isTextVisible=KO.prototype.isTextVisible;KO.prototype.remove=KO.prototype.remove;KO.prototype.destroy=KO.prototype.destroy;KO.prototype.append=KO.prototype.append;QO.prototype.ba=function(a){return!!a.enableHtmlCue&&!_.Dk()};QO.prototype.create=function(a){return new KO(a)};_.w(RO,_.Ir);RO.prototype.f=function(){_.uo(_.te,new QO)};RO.prototype.a=function(){_.so.has(_.te)&&(_.so["delete"](_.te),_.to.info("Removed factory: 'html'"))};RO.prototype.id=function(){return _.$f};_.H("clpp.htmlcue.HtmlCueComponent",RO);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();