(function(){var g={}; var _ = _ || {}
var f=function(window){var yy=function(a){switch(a.type){case 1:return vy;case 2:return wy;case 3:return xy}},Ay=function(a){var b=Object.keys(a).find(function(c){return zy.includes(c.toLowerCase())});return void 0!==b?a[b]:void 0},By=function(a,b){this.m=a;this.o=this.f=null;this.B=("000000"+(Math.random()*Math.pow(36,6)<<0).toString(36)).slice(-6);this.a=new _.Eh;this.g=b;this.A=this.l=this.h=!1;this.w=null;this.j=a.getNetworkEngine();this.G=this.ij.bind(this);this.C=this.dm.bind(this)},Dy=function(a){var b={debug:!0,
data:Cy(a)};a.f&&a.f.muxOptionsOverride&&_.N.Wc(a.f.muxOptionsOverride)&&(b=_.N.oa(b,a.f.muxOptionsOverride));b=_.N.oa(b,{getPlayheadTime:function(){return 1E3*a.m.getPosition()},getStateData:function(){a.g.debug("getStateData()");var c=a.m.getLoadedSource(),d=a.m.getTrackManager(),e=a.m.getSurface(),f={player_is_paused:a.m.isPaused(),player_is_fullscreen:e.isFullscreen(),video_source_duration:1E3*a.m.getDuration(),player_autoplay_on:!!a.m.getConfiguration().autoplay};if(c){var g=new _.Xj(c.url);
f.video_source_url=_.Yj(g);f.video_source_mime_type=c.type;c.name&&(f.video_title=c.name)}if(c=e.getContainer())f.player_width=c.offsetWidth,f.player_height=c.offsetHeight;(c=a.m.getSurface().getMedia())?c={videoWidth:c.videoWidth,videoHeight:c.videoHeight}:(c=a.m.getTrackManager().ka(),c={videoWidth:c.width,videoHeight:c.height});e=c;c=e.videoWidth;e=e.videoHeight;a.g.debug("Video dimensions: "+c+"x"+e);c&&e&&(f.video_source_height=c,f.video_source_width=e);(d=d.ja())&&d.language&&(f.player_language_code=
d.language);return f}});a.g.debug("Mux SDK options",b);return b},Cy=function(a){var b={env_key:a.f.envKey,video_title:a.o&&a.o.name||"",player_name:_.wa,player_software_name:_.wa,player_software_version:_.ja,player_mux_plugin_name:"CastlabsPlayer built-in Mux Plugin",player_mux_plugin_version:_.ja};(a=a.m.getConfiguration().viewerId)&&(b.viewer_user_id=a);return b},Ey=function(a){a.a.on(a.m,_.eg,function(){var b={player_playhead_time:1E3*a.m.getPosition()};a.emit(_.eg,b)});a.a.on(a.m,_.gf,function(){return a.emit(_.gf)});
a.a.on(a.m,_.gd,a.fj.bind(a));a.a.on(a.m,_.Tf,a.hj.bind(a));a.a.on(a.m,_.og,function(){return a.emit(_.Mf)});a.a.on(a.m,_.mg,function(){return a.emit(_.Lf)});a.a.on(a.m,_.ne,a.gj.bind(a));a.a.on(a.m,_.uc,function(){return a.emit("adbreakstart")});a.a.on(a.m,_.vc,function(){return a.emit("adbreakend")});a.a.on(a.m,_.Hc,function(){a.emit("adplay");a.emit("adplaying")});a.a.on(a.m,_.Dc,function(){return a.emit("adpause")});a.a.on(a.m,_.Fc,function(){a.emit("adplay");a.emit("adplaying")});a.a.on(a.m,
_.Ic,function(){return a.emit("adended")});a.a.on(a.m,_.zc,function(){return a.emit("adfirstquartile")});a.a.on(a.m,_.Cc,function(){return a.emit("admidpoint")});a.a.on(a.m,_.Jc,function(){return a.emit("adthirdquartile")});a.j.hd(a.G);a.j.Xf(a.C);a.a.on(a.m,_.ne,function(b){var c=b.detail;if(c&&1===c.category&&(b=(b=c.data)&&b.request,void 0!==b&&!0===(1===b.type||2===b.type||3===b.type)))if(7001===c.code){c=b.requestStartTimestamp;var d=new _.Xj(b.uris[b.uriIndex]);b={request_start:c,request_type:yy(b),
request_hostname:d.a};a.g.debug("onRequestCanceled()","Track event: requestcanceled",b);a.emit("requestcanceled",b)}else{d=b.requestStartTimestamp;var e=new _.Xj(b.uris[b.uriIndex]),f=c.data;b={request_start:d,request_type:yy(b),request_hostname:e.a,request_error:""+yy(b)+"LoadError",request_error_code:void 0===f?-1:void 0!==f.response?f.response.status:void 0!==f.status?f.status:-1,request_error_text:c.toString()};a.g.debug("onRequestFailed()","Track event: requestfailed",b);a.emit("requestfailed",
b)}})},Fy=function(a){_.Hh(a.a);a.j.ze(a.G);a.j.Fh(a.C)},Gy=function(){this.f=this.m=null;this.a=!1;this.g=new _.K("clpp.muxdata")},Hy=function(a){return!_.N.R(a)&&typeof a.init===_.qe&&typeof a.emit===_.qe},Iy=function(){},vy="manifest",wy="media",xy="encryption",zy=["x-request-id","cf-ray","x-amz-cf-id","x-akamai-request-id"];_.r=By.prototype;_.r.initialize=function(a,b,c){this.f=a;this.o=b;this.w=c;if(!this.h){try{this.h=!0,this.w.init(this.B,Dy(this))}catch(d){throw this.h=!1,Fy(this),new _.P(1,9,9302,null,d);}this.emit("playerready")}this.l&&!this.A&&(a=Cy(this),this.emit("videochange",a),this.l=!1);Ey(this)};_.r.release=function(){this.g.debug("release()");this.l?this.g.debug(_.ma):(Fy(this),this.l=!0,this.o=this.f=null)};_.r.destroy=function(){this.g.debug(_.Wd);this.A?this.g.debug(_.la):(this.A=!0,this.emit("destroy"))};
_.r.emit=function(a,b){if(null===this.w)throw new _.P(1,9,9301);this.w.emit(this.B,a,b)};_.r.fj=function(a){this.g.debug(_.Ue);var b=a.detail;a=this.m.getTrackManager();b&&b.bandwidth&&(b=b.bandwidth,(a=a.Qa())&&a.bandwidth&&(b+=a.bandwidth),this.emit("renditionchange",{video_source_bitrate:b}))};_.r.hj=function(a){this.g.debug(_.Ye);switch(a.detail.currentState){case _.To:this.m.getConfiguration().autoplay&&this.emit(_.gf);break;case _.Vo:this.emit(_.of);break;case _.Uo:this.emit(_.cf);break;case _.Oo:this.emit(_.me)}};
_.r.gj=function(a){this.g.debug(_.Ve);if(this.h&&(a=a.detail||null))if(10003===a.code)this.emit("aderror");else if(a.severity===_.Q){var b=a.message||"Player error";if(1===a.category||6100===a.code||6007===a.code)b="Download error",6100===a.code?b="Certificate request error":6007===a.code&&(b="License request error"),b=b+" castlabs-error-data:"+JSON.stringify(a.data);this.emit(_.ne,{player_error_code:a.code,player_error_message:b})}};
_.r.ij=function(a){var b=a.request;if(b=void 0!==b&&!0===(1===b.type||2===b.type||3===b.type))b=a.status,b=void 0!==b&&200<=b&&299>=b;if(b){b=a.request;var c=a.headers,d=b.bytesLoaded,e=b.requestStartTimestamp,f=b.startTime,g=b.endTime,h=e+a.responseStartMs;a=e+a.timeMs;f=f&&g?g-f:void 0;g=new _.Xj(b.uris[b.uriIndex]);a={request_start:e,request_type:yy(b),request_hostname:g.a,request_id:Ay(c),request_bytes_loaded:d,request_response_start:h,request_response_end:a,request_response_headers:c,request_media_duration:f,
request_url:_.Yj(g)};this.g.debug("onRequestCompleted()","Track event: requestcompleted",a);this.emit("requestcompleted",a)}};_.r.dm=function(a){a.requestStartTimestamp=Date.now()};_.w(Gy,_.rt);_.r=Gy.prototype;_.r.onPlayerCreated=function(a){this.m=a;this.f=new By(a,this.g)};
_.r.onContentWillLoad=function(a,b){var c=a.getConfiguration();c=_.N.Oa(c.muxdata);try{var d=[];typeof c===_.Te&&(c.envKey||d.push("envKey"));if(0<d.length)throw new _.P(1,9,9300,{missingKeys:d});var e=a.getConfiguration();d=null;if(this.a=!_.N.R(e.muxdata)&&typeof e.muxdata===_.Te){var f=e.muxdata;d=Hy(f.muxLib)?f.muxLib:window.mux;if(!Hy(d)){this.g.warn("Mux SDK is not loaded. Will do nothing.");this.a=!1;var g=new _.P(1,9,9301);this.U(a,g)}}else this.g.warn("Mux plugin is loaded but not configured. Will do nothing.");
var h=d;null!==h&&this.f.initialize(c,b,h)}catch(l){this.a=!1,this.U(a,l)}};_.r.onContentLoaded=function(){};_.r.onPlayerWillDestroy=function(){this.a&&(this.f.destroy(),this.m=this.f=null)};_.r.onPlayerWillRelease=function(){this.a&&this.f.release()};_.r.id=function(){return"mux"};_.r.emit=function(a,b){try{this.f.emit(a,b)}catch(c){throw null!==this.m&&this.U(this.m,c),c;}};_.r.U=function(a,b){a.trigger(new _.L(_.ne,{detail:b}))};_.H("clpp.muxdata.MuxDataPlugin",Gy);Gy.prototype.emit=Gy.prototype.emit;
Gy.Id="mux";Iy.prototype.create=function(){return new Gy};_.nq(new Iy);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();