(function(){var g={}; var _ = _ || {}
var f=function(window){var Sv='application/mp4; codecs\x3d"stpp.ttml"',Tv='application/mp4; codecs\x3d"stpp.ttml.im1i"',Uv='application/mp4; codecs\x3d"stpp.ttml.im1t"',Vv="backgroundColor",Wv="direction",Xv="displayAlign",Yv="region",Zv="sans-serif",$v="textAlign",aw="textDecoration",bw="writingMode",cw=function(a,b,c){this.h=a;this.f=b;this.a=c},dw=function(a,b,c){cw.call(this,a,[],c);this.j=b||""},ew=function(a,b,c){cw.call(this,a,b,c)},fw=function(a,b,c){a=a.f;for(var d=a.length-1;0<=d;d--){var e=b.get(a[d]);if(c in
e.a)return e.getAttribute(c)}return null},nw=function(a,b){var c=null;if(gw.test(a)){c=gw.exec(a);var d=Number(c[1]),e=Number(c[2]),f=Number(c[3]),g=Number(c[4]);g+=(Number(c[5])||0)/b.f;f+=g/b.frameRate;c=f+60*e+3600*d}else hw.test(a)?c=iw(hw,a):jw.test(a)?c=iw(jw,a):kw.test(a)?(c=kw.exec(a),c=Number(c[1])/b.frameRate):lw.test(a)?(c=lw.exec(a),c=Number(c[1])/b.a):mw.test(a)&&(c=iw(mw,a));return c},iw=function(a,b){var c=a.exec(b);return null==c||""===c[0]?null:(Number(c[4])||0)/1E3+(Number(c[3])||
0)+60*(Number(c[2])||0)+3600*(Number(c[1])||0)},ow=function(a){return a.split(":").pop()},pw=function(a){return a.replace(/(\d*\.?\d+)c/g,"$1em")},rw=function(a,b){for(;qw.test(a);){var c=qw.exec(a)[0];a=a.replace(c,parseInt(c,10)/b+"em")}return a},sw=function(a){return a?a.replace(/(\d*\.?\d+)%/g,function(b,c){return c/100+"em"}):""},tw=function(a,b,c,d,e,f,g){cw.call(this,a,f,g);this.w=b;this.A=c;this.o=d;this.l=e;this.j=[]},uw=function(a,b,c){a=fw(a,b,$v);if(!a&&c&&(a=fw(c,b,$v),!a&&"rltb"===fw(c,
b,bw)))return _.Kf;switch(a){case _.sd:return _.Zh;case _.Kf:case _.le:return _.Kf;default:return _.ye}},vw=function(a,b,c){if(_.R.ue(a.w))return document.createTextNode(_.R.Pf(a.w||""));if(a.A)return _.qp("br");for(var d=_.qp("span"),e=_.u(a.f),f=e.next();!f.done;f=e.next())_.rp(d,f.value);a=_.u(a.j);for(e=a.next();!e.done;e=a.next())d.appendChild(vw(c.get(e.value),b,c));return d},ww=function(a,b,c,d){this.frameRate=Number(a)||30;this.f=Number(b)||1;this.a=Number(d);0===this.a&&(this.a=a?this.frameRate*
this.f:1);c&&(a=/^(\d+) (\d+)$/g.exec(c))&&(this.frameRate*=Number(a[1])/Number(a[2]))},xw=function(a,b,c){cw.call(this,a,b,c)},Aw=function(a,b,c,d){var e=yw.exec(a);a=zw.exec(a);return typeof b===_.k&&0<b&&a?100*Number(a[c])/b:e?Number(e[c]):a?Number(a[c]):d},Bw=function(a,b){return typeof b===_.k&&0<b?_.ei:zw.test(a)?0:_.ei},Cw=function(a,b){cw.call(this,"root-container",[],b);this.j=a},Dw=function(a,b,c){return typeof a===_.k?a:typeof b===_.k?b:c},Ew=function(a,b){var c=a.getAttribute("extent");
return(c=zw.exec(c))?Number(c[b]):null},Gw=function(a){a=a.getAttribute("cellResolution");return(a=Fw.exec(a))?Number(a[2]):null},Hw=function(a,b,c){cw.call(this,a,b,c)},Iw=function(a){this.B=a;this.w=this.l=null;this.A=0;this.h=new Map;this.a=new Map;this.j=new Map;this.f=new Map;this.o=[]},Kw=function(a){return Jw.some(function(b){return b in a.attributes})},Lw=function(a,b){if(0===b.length)return[];for(var c=[],d=_.u(b),e=d.next();!e.done;e=d.next())e=e.value,a.a.has(e)&&c.push.apply(c,_.Og(Lw(a,
a.a.get(e).f)).concat([e]));return c},Nw=function(){return"inline-"+Mw++},Ow=function(a){this.a=a.firstChild;this.f=new Set},Pw=function(a,b,c,d,e,f){this.h=a;this.a=b;this.j=c;this.l=d;this.f=e;this.attributes=f},Qw=function(a){return ow(a.h.nodeName)},Rw=function(){this.a=new Map},Tw=function(a,b){if(a.a.has(b))return a.a.get(b);var c=null,d=null,e=[],f=[],g={},h=b.parentNode;if(h&&a.a.has(h)){var l=a.a.get(h);e=_.Og(l.l).concat();-1===["#text","span","br"].indexOf(b.nodeName)&&(c=l.a,d=l.j,f=_.Og(l.f).concat(),
g={},Sw.forEach(function(n){n in l.attributes&&(g[n]=l.attributes[n])}))}if(b.nodeType===b.ELEMENT_NODE){b.hasAttribute(Yv)&&(c=b.getAttribute(Yv));b.hasAttribute(_.Yf)&&f.push.apply(f,_.Og(b.getAttribute(_.Yf).split(" ")));d=Array.from(b.attributes).map(function(n){return n.name});d=_.u(d);for(h=d.next();!h.done;h=d.next()){h=h.value;var m=ow(h);g[m]=b.getAttribute(h)}d=g.backgroundImage}c=new Pw(b,c,d,e,f,g);a.a.set(b,c);return c},Uw=function(a){this.a=a;this.f=new DOMParser},Vw=function(a){this.f=
a},Ww=function(a){return String(Math.floor(a/3600)).padStart(2,"0")+":"+String(Math.floor(a/60%60)).padStart(2,"0")+":"+String(Math.floor(a%60)).padStart(2,"0")+"."+String(Math.floor(1E3*a%1E3)).padStart(3,"0")},Xw=function(){},Yw=function(a){this.a=new Uw(a);this.g=new _.K("clpp.ttml.Mp4TtmlParser")},Zw=function(){this.j=new Xw};cw.prototype.getId=function(){return this.h};cw.prototype.getAttribute=function(a){return this.a[a]};_.w(dw,cw);_.w(ew,cw);var gw=/^(\d{2,}):(\d{2}):(\d{2}):(\d{2})\.?(\d+)?$/,hw=/^(?:(\d{2,}):)?(\d{2}):(\d{2})$/,jw=/^(?:(\d{2,}):)?(\d{2}):(\d{2}\.\d+)$/,kw=/^(\d*(?:\.\d*)?)f$/,lw=/^(\d*(?:\.\d*)?)t$/,mw=/^(?:(\d*(?:\.\d*)?)h)?(?:(\d*(?:\.\d*)?)m)?(?:(\d*(?:\.\d*)?)s)?(?:(\d*(?:\.\d*)?)ms)?$/,yw=/^(\d{1,2}(?:\.\d+)?|100(?:\.0+)?)% (\d{1,2}(?:\.\d+)?|100(?:\.0+)?)%$/,zw=/^(\d+)px (\d+)px$/,Fw=/^(\d+) (\d+)$/,qw=/(\d+)px/,$w=/^(\d+px|\d+em|\d*\.?\d+c)$/,Jw=[Vv,"color",Wv,Xv,"fontFamily","fontSize","fontStyle","fontWeight",
"lineHeight","opacity","padding",$v,aw,"textOutline",bw,"zIndex"],Sw=["begin",_.le];_.w(tw,ew);
tw.prototype.build=function(a,b,c,d,e,f,g){var h=nw(this.a.begin,b);b=nw(this.a.end,b);if(null===h||null===b)return null;h+=c;b+=c;c=_.qp(_.Yd);for(var l=_.u(this.j),m=l.next();!m.done;m=l.next())c.appendChild(vw(g.get(m.value),e,g));g=new _.di(h,b,c.innerHTML.trim(),_.gg);g.cssClassList=_.Og(this.f).concat();g.textAlign=uw(this,e,null);g.writingMode=_.$h;g.line=-1;g.lineInterpretation=_.ai;g.lineAlign=_.bi;g.containerRows=Dw(null,Gw(a),15);if(this.o&&(f=f.get(this.o))){g.region=f.build(a,e);g.textAlign=
uw(this,e,f);a:switch(fw(f,e,bw)){case "tb":case "tblr":a=_.qg;break a;case "tbrl":a=_.rg;break a;default:a=_.$h}g.writingMode=a;a:switch(fw(f,e,Xv)){case _.sd:a=50;break a;case "after":a=-1;break a;default:a=0}g.line=a;a:switch(fw(f,e,Xv)){case _.sd:a=1;break a;default:a=_.ai}g.lineInterpretation=a;a:switch(fw(f,e,Xv)){case _.sd:e=_.sd;break a;default:e=_.bi}g.lineAlign=e}this.l&&(a=d.get(this.l))&&(d=a.getAttribute("encoding"),e=a.getAttribute("imageType")||a.getAttribute("imagetype"),a=a.j.trim(),
g.backgroundImage=("PNG"===e&&"Base64"===d&&0<a.length?"data:image/png;base64,"+a:null)||"");return g};_.w(xw,ew);
xw.prototype.build=function(a,b){var c=new _.gi;c.id=this.getId();var d=Dw(a.j.containerWidth,Ew(a,1),720),e=Dw(a.j.containerHeight,Ew(a,2),480);a:switch(fw(this,b,Xv)){case "after":var f="flex-start";break a;case _.sd:f=_.sd;break a;default:f="flex-end"}c.displayAlign=f;a:switch(fw(this,b,bw)){case "tb":case "tblr":f="row-reverse";break a;case "tbrl":f="row";break a;default:f=_.Kd}c.writingMode=f;f=this.getAttribute("extent")||fw(this,b,"extent");c.width=Aw(f,d,1,100);c.widthUnits=Bw(f,d);c.height=
Aw(f,e,2,100);c.heightUnits=Bw(f,e);f=this.getAttribute("origin")||fw(this,b,"origin");c.viewportAnchorX=Aw(f,d,1,0);c.viewportAnchorY=Aw(f,e,2,0);c.viewportAnchorUnits=Bw(f,d);c.cssClassList=_.Og(this.f).concat();return c};_.w(Cw,cw);_.w(Hw,cw);
Hw.prototype.build=function(a){var b=null;var c=Gw(a);c&&(b=Dw(a.j.containerHeight,Ew(a,2),480)/c);b=Dw(a.j.fontSizeRadix,b,16);a=[];c="::ttml ."+this.h+", ::ttml ."+this.h+" * {";for(var d=_.u(ax.entries()),e=d.next();!e.done;e=d.next()){var f=_.u(e.value);e=f.next().value;f=f.next().value;e in this.a&&(c+=f+":"+pw(this.a[e])+";")}a:{if("unicodeBidi"in this.a){d=this.a.unicodeBidi;e="";switch(d){case "normal":case "embed":e=d;break;case "bidiOverride":e="bidi-override"}if(0<e.length){d="unicode-bidi:"+
e+";";break a}}d=""}c+=d;a:{if("textOutline"in this.a){d=this.a.textOutline.split(" ");e="black";f=".4em";var g=d[0]&&d[0].trim(),h=d[1]&&d[1].trim(),l=d[2]&&d[2].trim();3===d.length&&!$w.test(g)&&$w.test(h)&&$w.test(l)?(e=g,f=h):2===d.length&&!$w.test(g)&&$w.test(h)?(e=g,f=h):2===d.length&&$w.test(g)&&$w.test(h)&&(f=g);if(""!==f){f=pw(f);d="text-shadow:0 0 "+(f+" "+e+",0 0 ")+(f+" "+e+",0 0 ")+(f+" "+e+";");break a}}d=""}c+=d;"textShadow"in this.a?(d=sw(this.a.textShadow),d=pw(d),d="text-shadow:"+
d+";"):d="";c=c+d+("fontFamily"in this.a?"font-family:"+this.a.fontFamily.replace("monospaceSansSerif","monospace").replace("monospaceSerif","monospace").replace("proportionalSansSerif",Zv).replace("proportionalSerif",Zv).replace("sansSerif",Zv).replace("default",Zv)+";":"");a:{if(aw in this.a){d=[];e=_.u(this.a.textDecoration.split(" "));for(f=e.next();!f.done;f=e.next())switch(f=f.value,f){case "underline":case "overline":d.push(f);break;case "lineThrough":d.push("line-through")}if(0<d.length){d=
"text-decoration:"+d.join(" ")+";";break a}}d=""}e="padding"in this.a?"border: solid transparent;border-width:"+pw(this.a.padding)+";":"";c=c+d+e;"lineHeight"in this.a?(d="",e=this.a.lineHeight,e=pw(e),e=rw(e,b),d=d+"line-height:"+e+";"):d="";a.push(c+d+"}");a:{if("fontSize"in this.a&&(c=this.a.fontSize.split(" "),d=null,1===c.length&&(d=c[0]),2===c.length&&(d=c[1]),d)){d=d.trim();d=pw(d);d=rw(d,b);b="font-size:"+d+";";break a}b=null}b&&(c="::ttml ."+this.h+" .clpp-text-wrapper {",a.push(c+b+"}"),
c="::ttml .clpp-text-wrapper__"+this.h+" {",a.push(c+b+"}"));return a};var ax=new Map([[Vv,"background-color"],["color","color"],[Wv,Wv],["fontStyle","font-style"],["fontWeight","font-weight"],["opacity","opacity"],["zIndex","z-index"]]);Iw.prototype.zd=function(){var a=this;return this.o.map(function(b){return b.build(a.l,a.w,a.A,a.h,a.a,a.j,a.f)}).filter(function(b){return null!=b})};var Mw=0;Ow.prototype.Vc=function(){return!!this.a};Ow.prototype.next=function(){if(!this.a)return null;var a=this.a;do this.f.add(a),a.nodeType!==Node.TEXT_NODE&&!bx.has(ow(a.nodeName))||cx.has(ow(a.nodeName))||!a.firstChild||this.f.has(a.firstChild)?a.nextSibling?a=a.nextSibling:a=a.parentNode:a=a.firstChild;while(a&&(this.f.has(a)||a.nodeType!==Node.TEXT_NODE&&!bx.has(ow(a.nodeName))));var b=this.a;this.a=a;return b};
var bx=new Set(["tt","head","layout",_.Le,_.ue,Yv,"styling",_.Yf,"body",_.Yd,"p","span","br"]),cx=new Set([_.Yf,_.ue]);Pw.prototype.getId=function(){return this.attributes.id};Uw.prototype.parseInit=function(){};
Uw.prototype.parseMedia=function(a,b,c){c&&c.length||(c=[a.byteLength]);var d=_.N.Oa(this.a.ttml||{}),e=_.Ui(a,0,c[0]);e=_.R.Z(e);if(""===e)return{cues:[],styles:[]};var f=null;try{f=this.f.parseFromString(e,_.dg)}catch(n){throw new _.P(_.Q,2,2005,"Failed to parse TTML.");}d=new Iw(d);e=new Rw;f=new Ow(f);b=b.periodStart;typeof b===_.k&&(d.A=b);b=c[0];for(var g=1;g<c.length;++g){var h=c[g],l=_.Ui(a,b,h);l=_.dj(l);var m="urn:mpeg:14496-30:subs:"+g;d.h.set(m,new dw(m,l,{imageType:"PNG",encoding:"Base64"}));
b+=h}for(;f.Vc();)a=f.next(),a=Tw(e,a),"tt"===Qw(a)&&(d.l=new Cw(d.B,Object.assign({},a.attributes))),"tt"===Qw(a)&&(d.w=new ww(a.attributes.frameRate,a.attributes.subFrameRate,a.attributes.frameRateMultiplier,a.attributes.tickRate)),Qw(a)!==_.ue||a.attributes.begin||a.attributes.end||(c="#"+a.getId(),d.h.set(c,new dw(c,a.h.textContent,a.attributes))),Qw(a)===_.ue&&a.attributes.begin&&a.attributes.end?(c="#"+Nw(),b=new dw(c,a.h.textContent,a.attributes),d.h.set(c,b),c=b):c=null,c&&(a.j=c.getId()),
Qw(a)===_.Yf&&(c=a.getId()||Nw(),b=new Hw(c,a.f,Object.assign({},a.attributes)),d.a.set(c,b),a.a&&d.j.get(a.a).f.push(c)),Qw(a)!==_.Yf&&Kw(a)?(c=Nw(),b=new Hw(c,[],Object.assign({},a.attributes)),d.a.set(c,b),c=b):c=null,c&&a.f.push(c.getId()),Qw(a)!==_.Yd||!a.attributes.extent&&!a.attributes.origin?c=null:(c=Nw(),b=new xw(c,Lw(d,a.f),Object.assign({},a.attributes)),d.j.set(c,b),c=b),c&&(a.a=c.getId()),Qw(a)!==Yv?c=null:(c=a.getId(),b=new xw(c,Lw(d,a.f),Object.assign({},a.attributes)),d.j.set(c,b),
c=b),c&&(a.a=c.getId()),c=a.l,-1===["#text","span","br"].indexOf(Qw(a))||0===c.length?c=null:(g=c[c.length-1],d.f.has(g)?(c=Nw(),b=new tw(c,"#text"===a.h.nodeName?a.h.textContent:null,"br"===Qw(a),a.a,a.j,Lw(d,a.f),a.attributes),d.f.set(c,b),(g=d.f.get(g))&&g.j.push(c),c=b):c=null),c&&a.l.push(c.getId()),"p"===Qw(a)||a.j?(c=Nw(),b=new tw(c,null,!1,a.a,a.j,Lw(d,a.f),a.attributes),d.f.set(c,b),d.o.push(b),c=b):c=null,c&&a.l.push(c.getId());e=d.zd();f=[];a=_.u(d.a.values());for(c=a.next();!c.done;c=
a.next())f.push.apply(f,_.Og(c.value.build(d.l)));return{cues:e,styles:f}};Vw.prototype.a=function(a){a=(new Uw(this.f)).parseMedia(a,{periodStart:0,segmentStart:null,segmentEnd:0}).cues;var b="WEBVTT\n\n";a=_.u(a);for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=Ww(c.startTime)+" --\x3e "+Ww(c.endTime),e=[];switch(c.textAlign){case _.ye:e.push("align:left");break;case _.Kf:e.push("align:right");break;case _.Zh:e.push("align:middle");break;case _.ye:e.push("align:start");break;case _.Kf:e.push("align:end")}switch(c.writingMode){case _.qg:e.push("vertical:lr");break;
case _.rg:e.push("vertical:rl")}b+=d+(e.length?" "+e.join(" "):"")+"\n";b+=c.payload+"\n\n"}return _.R.Va(b)};Xw.prototype.probe=function(a,b){return a===_.Xc&&b===_.cg};Xw.prototype.create=function(a){return new Vw(a)};Yw.prototype.parseInit=function(a){var b=!1;(new _.mm).L(_.Oe,_.nm).L(_.fg,_.nm).L(_.Je,_.nm).L(_.Ne,_.nm).L(_.Vf,_.nm).Y(_.Xf,_.om).L("stpp",function(c){b=!0;c.parser.stop()}).parse(a);if(!b)throw new _.P(_.Q,2,2007);};
Yw.prototype.parseMedia=function(a,b){var c=this,d=!1,e=[],f=[],g=[];(new _.mm).L("moof",_.nm).L("traf",_.nm).Y("subs",function(h){for(var l=_.W(h.reader),m=0;m<l;++m){h.reader.skip(4);for(var n=_.hm(h.reader),p=0;p<n;++p){var q=1===h.version?_.W(h.reader):_.hm(h.reader);g.push(q);h.reader.skip(6)}}}).L(_.Ie,_.pm(function(h){d=!0;h=c.a.parseMedia(h,b,g);e=e.concat(h.cues);f=f.concat(h.styles)})).parse(a);d||this.g.warn("Couldn't find the mdat box");return{cues:e,styles:f}};_.w(Zw,_.Ir);Zw.prototype.f=function(){_.ft[_.Xc]=Uw;_.ft[_.Vc]=Yw;_.ft[Sv]=Yw;_.ft[Uv]=Yw;_.ft[Tv]=Yw;_.ok.push(this.j)};Zw.prototype.a=function(){_.gt(_.Xc);_.gt(_.Vc);_.gt(Sv);_.gt(Uv);_.gt(Tv);_.qk(this.j)};Zw.prototype.id=function(){return"subtitles-ttml"};_.H("clpp.ttml.TtmlComponent",Zw);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();