(function(){var g={}; var _ = _ || {}
var f=function(window){var MJ="An unknown error occurred while trying to get volume",NJ="Cannot get loading rendition due to platform limitations",OJ="PARAM_START_POSITION",PJ="SecurityError",QJ="The require privilege is: http://tizen.org/privilege/tv.audio",RJ="|STARTBITRATE\x3d",SJ=function(a,b,c){function d(e){c.call(a,e);a.removeEventListener(b,d)}a.addEventListener(b,d)},TJ=function(a,b){this.h=a;this.o=null;this.a=_.Se;this.l=null;this.j=!1;this.f=new Map;this.D=b;this.g=new _.K("clpp.tizen.DrmEngine")},WJ=function(a){var b,
c,d;return _.E(function(e){if(1==e.a){b=a.a===_.Rd||a.a===_.Pd;if(!b)throw new _.P(_.Q,6,6001,"The key system "+a.a+" is not supported by the player or the platform");c=a.f.get(a.a);if(!c.Jd)throw new _.P(_.Q,6,6012,"No license server given for "+a.a);_.A(e,2);return a.a===_.Rd?_.x(e,UJ(a),5):_.x(e,VJ(a,c),5)}if(2!=e.a)return a.o={keySystem:a.a,licenseServerUri:c.Jd,distinctiveIdentifierRequired:!1,persistentStateRequired:c.Ff,audioRobustness:"",videoRobustness:"",serverCertificate:null,initData:[],
keyIds:[],periodId:null},_.ah(e,0);d=_.C(e);a.g.error("Error while configuring CDM for "+a.a,d);throw new _.P(_.Q,6,6005,{message:JSON.stringify(d)});})},VJ=function(a,b){var c,d,e,f;return _.E(function(g){c=XJ;d=YJ;e={};e[d.Xh]=!b.Ff;e[d.Yh]=b.Jd;""!==b.customData&&(e[d.Wh]=b.customData);f=JSON.stringify(e);a.g.debug("PlayReady properties: ",f);try{webapis.avplay.setDrm(c.PLAYREADY,"SetProperties",f)}catch(h){throw h;}_.y(g)})},UJ=function(a){var b;return _.E(function(c){b=XJ;try{webapis.avplay.setDrm(b.Vd,
"Initialize",""),webapis.avplay.setDrm(b.Vd,"widevine_app_session",a.l.id),webapis.avplay.setDrm(b.Vd,"widevine_data_type",a.l.type)}catch(d){throw d;}_.y(c)})},ZJ=function(a,b){var c,d,e,f,g,h,l,m,n,p,q,t,v,z,D,G,F;_.E(function(B){if(1==B.a){c=XJ;d=a.f.get(a.a);a.g.debug("DRM Challenge data: ",b.challenge);e=atob(b.challenge);f=new Uint8Array(e.length);for(g=0;g<e.length;++g)f[g]=e.charCodeAt(g);h=b.serverurl&&""!==b.serverurl?b.serverurl:d.Jd;l=_.rj([h],_.oj());l.type=3;l.body=f.buffer;l.method=
"POST";_.A(B,2);return _.x(B,a.D.Gb.fetch(l).O,4)}if(2!=B.a){m=B.f;if(a.j){n=_.Ui(m.data);p=n.byteLength;q="";for(t=0;t<p;t++)q+=String.fromCharCode(n[t]);v=btoa(q);z=b.session_id+OJ+(v+OJ);a.g.debug("Widevine license params",z);try{webapis.avplay.setDrm(c.Vd,"widevine_license_data",z)}catch(I){a.g.error("License response rejected by CDM"),D=new _.P(_.Q,6,6008,{browserError:JSON.stringify(I)}),a.D.onError(D)}}return _.ah(B,0)}G=_.C(B);a.g.error("License request failed.",JSON.stringify(G));F=new _.P(_.Q,
6,6007,{message:_.ab,url:G.data.url,status:G.data.status||NaN,response:G.data.response||"",headers:G.data.headers||{}},G);a.D.onError(F);_.y(B)})},$J=function(a){this.m=a;this.a=this.m.a;this.f=_.Ho;this.j=_.Io;this.w=(new Date).getTime();this.l=!1;this.o=-1;this.h=2;this.g=new _.K("clpp.tizen.StateManager")},bK=function(a,b){if(a.f!==b)if(a.f===_.So&&b!==_.Ho)a.g.debug(_.Uy+aK(b));else{var c=(new Date).getTime();a.j=a.f;a.f=b;a.f===_.Mo?(a.o=(new Date).getTime(),a.m.trigger(new _.L(_.jd,{detail:{bufferedTimeMS:-1,
reason:a.h}}))):a.j===_.Mo&&a.m.trigger(new _.L(_.id,{detail:{bufferedTimeMS:c-a.o,reason:a.h}}));var d={currentState:a.f,previousState:a.j,timeSinceLastStateChangeMS:c-a.w};a.w=c;a.m.trigger(new _.L(_.Tf,{detail:d}));a.g.debug("State changed:",aK(a.j),"-\x3e",aK(a.f))}},aK=function(a){return Object.keys(_.Qo)[a]},eK=function(a){if(a.l){var b=a.a.getState(),c=a.f;switch(b){case cK:c=_.Vo;break;case dK:c=_.Uo;break;default:a.m.isEnded()?c=_.Oo:a.g.debug("Inconsistent AVPlay playback state:",b)}bK(a,
c)}},fK=function(){this.o=this.A=this.f=this.h=this.B=this.m=this.j=this.a=null;this.C=!1;this.w=!0;this.l=null;this.g=new _.K("clpp.tizen.TextStreamer")},gK=function(a){if(!a)return!1;a=a.periods;for(var b=!1,c=0;c<a.length;c++)b=b||0<a[c].textStreams.length;return b},hK=function(a){var b,c;return _.E(function(d){if(1==d.a)return b=a.m.getConfiguration(),c=null,_.x(d,_.Cs(a.B.url,a.m.getNetworkEngine(),b.manifest.attemptParameters,a.B.type||null),2);(c=d.f)&&c.configure(b.manifest);return d["return"](c)})},
iK=function(a){var b=document.createElement(_.sg),c=new _.KA,d=new _.Sz(function(){return null}),e=a.m.getTextDisplayer();return new _.MA(b,c,e,d,a.m.getConfiguration())},jK=function(a){var b={Cb:function(){return a.m.getPosition()},X:a.h,Gb:a.m.getNetworkEngine(),wf:a.tj.bind(a),vf:a.sj.bind(a),onError:a.U.bind(a),nh:function(){},onEvent:function(){},rh:a.uj.bind(a),xe:function(){},ef:function(){return new _.RB},Se:function(){return!1},vd:null};return new _.PC(a.a,b)},kK=function(a){var b=a.m.getPosition(),
c=null;a=_.u(a.a.periods);for(var d=a.next();!d.done;d=a.next())d=d.value,d.startTime<=b&&(c=d);return c},lK=function(a){a.g.debug("getTextStreams()",a.a);if(a.a){var b=[],c=a.a.periods;a.g.debug("getting text streams");for(var d=0;d<c.length;d++)if(a.g.debug(c[d].startTime,a.m.getPosition()),c[d].startTime<=a.m.getPosition()){b=c[d].textStreams;break}a=b}else a=[];b=[];for(d=c=0;d<a.length;d++){var e=new _.Oj(String(c++),_.S);e.mimeType=a[d].mimeType;e.language=a[d].language;e.roles=a[d].roles;e.kind=
a[d].kind||_.oz;var f=new _.Wj(String(a[d].id),e);f.bandwidth=a[d].bandwidth||null;e.renditions.push(f);b.push(e)}return b},mK=function(a){if(a.h&&!a.h.getTextDisplayer().isTextVisible())return null;if(a.f){var b=_.SC(a.f,_.bg),c=null;if(b){a=lK(a);for(var d=0;d<a.length;d++)if(a[d].renditions[0].id===String(b.id)){c=a[d].renditions[0];break}}return c}return null},nK=function(a,b){a.g.debug("Set active track",b);if(b&&(a.o=b.language,a.A=b.roles[0]||"",a.C=b.kind===_.oe,a.a&&a.f)){a.setTextVisibility(!0);
var c=kK(a),d=b.renditions[0];(c=c.textStreams.find(function(e){return String(e.id)==d.id}))?(a.w?(a.g.debug("Switching period defer text selection"),a.l=c):(_.cD(a.f,c,!0,0),a.m.trigger(new _.L(_.nl))),a.o=c.language):a.g.error(_.Ty,d.id)}},oK=function(){this.h=this.a=this.m=null;this.f={};this.g=new _.K("clpp.tizen.TrackManager");this.w=this.l=this.j=null;this.A=!1;this.o=1},pK=function(a,b){a.m.trigger(new _.L(_.wg,{details:{width:b.width,height:b.height,bandwidth:b.bandwidth,track:b.track,abrSelection:a.a.o}}))},
qK=function(a){var b=a.ka();b&&a.m.trigger(new _.L(_.gd,{detail:{width:b.width,height:b.height,bandwidth:b.bandwidth,rendition:b}}))},rK=function(a){var b=a.m.getConfiguration(),c=_.Th(b.preferredAudioLanguage||[]),d=a.f[_.T]||[];if(d.length){var e=null;c.some(function(g){e=_.Gz(g,d.map(function(h){return h.language}));return!!e});if(e){var f=d.filter(function(g){return g.language===e});c=f[0];1<f.length&&b.preferredAudioRole&&(f=f.filter(function(g){return 0<=g.roles.indexOf(b.preferredAudioRole)}),
0<f.length&&(c=f[0]));a.g.debug("Setting audio track with preferred language:",e);a.za(c)}else a.g.debug("Preferred language(s) not available")}else a.g.debug("Could not set preferred audio language")},vK=function(a,b){if(b){var c=b.track.type.toUpperCase();sK(a.a,c,Number(b.id)).then(function(){c===tK&&(a.j=b,a.m.trigger(new _.L(_.ml)));c===uK&&(a.l=b,a.m.trigger(new _.L(_.nl)))})["catch"](function(){a.g.error("Could not select "+c+" track.")})}else a.g.debug("Must provide valid rendition")},wK=
function(a,b,c){var d=_.Ni(b.language||_.hg);c.language=_.Pj(d);c.originalLanguage=d;c.channelsCount=b.channels?Number(b.channels):null;c.mimeType=_.dd;a=new _.Wj(String(a),c);a.track=c;a.codec=b.fourCC||null;a.bandwidth=b.bit_rate||null;return a},xK=function(a,b,c){c.mimeType=_.ug;a=new _.Wj(String(a),c);a.track=c;a.width=b.Width||null;a.height=b.Height||null;a.bandwidth=b.Bit_rate?Number(b.Bit_rate):null;a.codec=b.fourCC||null;return a},yK=function(a,b,c){b=_.Ni(b.track_lang||_.hg);c.mimeType="text/ttml";
c.language=_.Pj(b);c.originalLanguage=b;c.kind=_.oz;return new _.Wj(String(a),c)},zK=function(a,b){var c=null;try{c=JSON.parse(b)}catch(d){a.g.warn("Couldn't retrieve extra infos from stream."),c=null}return c},CK=function(a,b){function c(n,p){for(var q=0;q<n.length;q++)if(n[q].language===p)return n[q];return null}var d={};if(0>=b.length)return d;for(var e=b.filter(function(n){return n.type===AK}),f=b.filter(function(n){return n.type===tK}),g=[],h=0;h<f.length;h++){var l=zK(a,f[h].extra_info);if(l){var m=
_.Ni(l.language||_.hg);m=_.Pj(m);m=c(g,m);m||(m=new _.Oj(String(a.o++),_.T),g.push(m));m.renditions.push(wK(f[h].index,l,m))}else a.g.warn("Skipping audio stream with no extra info")}f=new _.Oj(String(a.o++),_.Qj);for(h=0;h<e.length;h++)(l=zK(a,e[h].extra_info))?f.renditions.push(xK(e[h].index,l,f)):a.g.warn("Skipping video stream with no extra info");e=[];e=a.h?lK(a.h):BK(a,b);d[_.Qj]=[f];d[_.T]=g;d[_.S]=e;return d},BK=function(a,b){for(var c=b.filter(function(h){return h.type===uK}),d=[],e=0;e<
c.length;e++){var f=zK(a,c[e].extra_info);if(f){var g=new _.Oj(String(a.o++),_.S);g.renditions.push(yK(c[e].index,f,g));d.push(g)}else a.g.warn("Skipping text stream with no extra info")}return d},DK=function(a,b){for(var c=a.f[_.Qj]||[],d=[],e=0;e<c.length;e++)for(var f=0;f<c[e].renditions.length;f++)_.N.ta(c[e].renditions[f],b,Object.keys(b))&&d.push(c[e].renditions[f]);return d[0]||null},EK=function(a,b,c){a=a.f[c]||[];b=String(b.index);c=null;for(var d=0;d<a.length;d++)for(var e=0;e<a[d].renditions.length;e++)if(a[d].renditions[e].id===
b){c=a[d].renditions[e];break}return c},GK=function(a,b){if(b===_.S&&a.h)return mK(a.h);var c=FK(a.a)||[];if(0===c.length)return null;c=c.filter(function(e){return e.type===b.toUpperCase()})[0];var d=null;b===_.Qj&&(d=zK(a,c.extra_info),d=DK(a,{width:d.Width,height:d.Height}));b===_.T&&(c?(d=EK(a,c,_.T),a.j=d):d=a.j);b===_.S&&(c?(d=EK(a,c,_.S),a.l=d):d=a.l);return d},HK=function(a){_.tl.call(this);this.m=a;this.h=null;this.g=new _.K("clpp.tizen.Middleware");this.C=1;this.B=!1;this.l=null;this.G=0;
this.o=!0;this.f=!1;this.a=null;this.A=1;this.w=!1;this.j={}},IK=function(a){return _.E(function(b){tizen.systeminfo.getPropertyValue("DISPLAY",function(c){a.A=c.resolutionWidth/1920;a.g.debug("Display resolution ratio: ",a.A)},function(c){a.g.debug("Could not load DISPLAY property");throw c;});_.y(b)})},KK=function(a){try{webapis.avplay.setListener({onbufferingstart:a.nj.bind(a),onbufferingprogress:a.mj.bind(a),onbufferingcomplete:a.lj.bind(a),onstreamcompleted:a.qj.bind(a),oncurrentplaytime:function(b){a.trigger(new _.L(JK,
{currentTime:b}))},onevent:a.pj.bind(a),onsubtitlechange:a.rj.bind(a),ondrmevent:a.oj.bind(a),onerror:a.U.bind(a)})}catch(b){a.g.error(b)}},LK=function(a){var b=!!a.m.getTrackManager().Ha();try{webapis.avplay.setSilentSubtitle(!b)}catch(c){a.g.debug("Could not set AVPlay subtitle config",c)}},MK=function(a,b){try{var c=b.estimatedBandwidth||0,d=b.currentBandwidth||0;a.g.debug({estimatedBandwidth:c,Zm:d});0!==c&&0!==d&&c>=1.15*d&&webapis.avplay.setStreamingProperty("ADAPTIVE_INFO",RJ+d)}catch(e){a.g.debug(e)}},
NK=function(a,b){try{webapis.avplay.setStreamingProperty("ADAPTIVE_INFO","|BITRATES\x3d"+b+RJ+b)}catch(c){throw a.g.debug("Could not set fixed bandwidth",c),c;}},QK=function(a){return{position:a.getPosition(),state:a.m.getState(),eg:a.getState(),playbackRate:a.getPlaybackRate(),isLive:a.isLive(),duration:a.getDuration(),isMuted:OK(a),volume:a.getVolume(),vm:PK(a),Ij:FK(a)}},SK=function(a){var b,c;return _.E(function(d){if(1==d.a)return _.x(d,RK(),2);if(3!=d.a)return b=new Promise(function(e){(new _.uk(e)).aa(5)}),
_.x(d,Promise.race([IK(a).then(function(){return!0}),b.then(function(){return!1})]),3);c=d.f;if(!c)return a.g.debug("Took to long for the SDK to be ready"),d["return"](Promise.reject("SDK Timeout"));_.y(d)})},YK=function(a,b,c){var d,e,f,g,h,l,m,n;return _.E(function(p){switch(p.a){case 1:a.l=_.Zo(b);d=a.G;e=c||{estimatedBandwidth:0,currentBandwidth:0,nextBandwidth:null,currentPosition:0};a.g.debug("Loading manifest URL: "+a.l[d].url);f=b.startTime||void 0;a.f&&(a.trigger(new _.L(TK)),f=c.currentPosition);
_.A(p,2);g=a.l[d].url;h=a.l[d].type;h!==_.Tc||g.includes(".mpd")||(l=new URL(g),l.searchParams.append("cl-ext",".mpd"),g=l.toString());webapis.avplay.open(g);e.nextBandwidth?(NK(a,e.nextBandwidth),a.o=!1):(a.o||MK(a,e),a.o=!0);KK(a);if(!b.drm||!b.drm.env){a.g.debug("No DRM configuration was provided. Assuming clear content");p.F(4);break}m={onError:function(q){return a.m.onError(q)},Gb:a.m.getNetworkEngine()};a.h=new TJ(b.drm,m);return _.x(p,a.h.init(),4);case 4:return a.f||a.trigger(new _.L(UK)),
_.x(p,VK(a),6);case 6:a.f||a.trigger(new _.L(WK));f&&typeof f===_.k&&0<f&&a.seek(f)["catch"](function(q){a.g.debug("Couldn't set start position",q)});a.f||(b.volume&&a.setVolume(b.volume),b.muted&&XK(a,b.muted),b.autoplay&&a.m.play()["catch"](function(q){a.g.debug("Autoplay failed",q)}));_.ah(p,0);break;case 2:throw n=_.C(p),a.g.debug("Error while attempting to load source."),n;}})},VK=function(a){return _.E(function(b){a.g.debug("avplay.prepare()");return b["return"](new Promise(function(c,d){try{webapis.avplay.prepareAsync(function(){a.g.debug("AVPlay is ready!");
LK(a);c()},function(e){a.g.debug("prepareAsync failed",e);d(e)})}catch(e){a.g.debug("Failed to prepare media player for playback"),d(e)}}))})},ZK=function(a,b,c){a.g.debug("switchVideoTrack()");try{var d={estimatedBandwidth:parseInt(webapis.avplay.getStreamingProperty("CURRENT_BANDWITH"),10),currentBandwidth:b,nextBandwidth:c,currentPosition:a.getPosition()};a.a=QK(a);a.f=!0;webapis.avplay.stop();webapis.avplay.close();return a.load(a.m.getConfiguration(),d).then(function(){var e=a.a.eg;a.f=!1;a.a=
null;return e===dK?a.pause():a.play()})}catch(e){return Promise.reject(e)}},PK=function(a){return a.f&&a.a?a.a.vm:webapis.avplay.getTotalTrackInfo()},FK=function(a){return a.f&&a.a?a.a.Ij:webapis.avplay.getCurrentStreamInfo()},sK=function(a,b,c){b=b.toUpperCase();b===uK&&$K(a,!0);var d=a.j[b];d&&(d.Be.stop(),a.j[b]=null,a.g.debug("Cancelled pending track switch for "+b));return new Promise(function(e,f){function g(h,l,m){m=void 0===m?!1:m;try{webapis.avplay.setSelectTrack(h,l),a.j[h]=null,e()}catch(n){a.g.debug("Could not set "+
h+" track. Trying again...AVPlay state: "+(a.getState()+", buffering: ")+a.w,n),!1===m&&(a.j[h]={type:h,index:l,bg:0,Be:new _.uk(function(){return g(h,c,!0)})}),(l=a.j[h])&&3>l.bg?(!a.w&&++l.bg,l.Be.aa(a.w?.5:.25)):(a.g.debug("Could not set track after multiple attempts.Giving up..."),l&&l.Be.stop(),a.j[h]=null,f())}}g(b,c)})},$K=function(a,b){var c=a.m.getTextDisplayer();c&&c.setTextVisibility(b);c=a.m.h;try{c||webapis.avplay.setSilentSubtitle(!b)}catch(d){a.g.debug("Could not set text track visibility",
d)}},XK=function(a,b){try{tizen.tvaudiocontrol.setMute(b)}catch(c){switch(c.name){case PJ:a.g.warn("The application does not have the privilege to set mute.",QJ);break;default:a.g.warn(MJ,c)}}},OK=function(a){var b=null;try{b=tizen.tvaudiocontrol.isMute()}catch(c){switch(c.name){case PJ:a.g.warn("The application doesn't have the privilege to get the mute state.",QJ);break;default:a.g.warn(MJ,c)}}return!!b},RK=function(){return new Promise(function(a,b){if(window.webapis)a();else{var c=document.createElement("script");
SJ(c,"load",function(d){return a(d)});SJ(c,_.ne,function(d){return b(d)});c.src="$WEBAPIS/webapis/webapis.js";document.querySelector("head").appendChild(c)}})},aL=function(){_.tl.call(this);this.a=new HK(this);this.f=new $J(this);this.configuration=this.B=_.zl();this.w=null;this.g=new _.K("clpp.tizen.Player");this.j=null;this.l=new oK;this.C=new _.Kj;this.o=this.h=null;this.A=!1},bL=function(a){if("NONE"!==a.a.getState()){var b=a.j.getBoundingClientRect();a=a.a;var c=Math.floor(b.left*a.A),d=Math.floor(b.top*
a.A),e=Math.floor(b.width*a.A);b=Math.floor(b.height*a.A);a.g.debug("Setting display area to","x:",c,"y:",d,"width:",e,"height:",b);webapis.avplay.setDisplayRect(c,d,e,b);0===c&&0===d&&1920===e&&1080===b&&webapis.avplay.setDisplayMethod("PLAYER_DISPLAY_MODE_LETTER_BOX")}else a.g.debug("Could not apply dimension. Player state "+a.a.getState())},cL=function(){},dL=function(){};
TJ.prototype.init=function(){var a=this,b,c,d,e,f,g;return _.E(function(h){if(1==h.a){b=_.Ul[a.h.env]||null;if(!b)throw a.g.debug(_.za,_.Mb+a.h.env+_.ca),new _.P(_.Q,6,6015,_.Aa+a.h.env+"' is missing.");a.l={id:String(Math.floor(1E4*Math.random())),type:"MPEG-DASH"};c=Object.keys(a.h.customData||{}).length?btoa(JSON.stringify(a.h.customData)):"";d=_.Wl(b,a.h.customData);(e=d[_.Pd])&&a.f.set(_.Pd,{Jd:e.licenseUrl||"",customData:c,Ff:!1});(f=d[_.Rd])&&a.f.set(_.Rd,{Jd:f.licenseUrl||"",customData:c,
Ff:!1});if(0===a.f.size)throw new _.P(_.Q,6,6E3);if((g=a.h.preferredDrmSystem)&&a.f.get(g))a.a=g;else if(a.f.get(_.Pd))a.a=_.Pd;else if(a.f.get(_.Rd))a.a=_.Rd;else throw new _.P(_.Q,6,6001,"Configuration for the target system is missing.");return _.x(h,WJ(a),2)}a.j=!0;_.y(h)})};TJ.prototype.release=function(){var a=this;return _.E(function(b){a.j=!1;a.o=null;a.a=_.Se;a.l=null;a.f=new Map;_.y(b)})};TJ.prototype.getDrmInfo=function(){return this.o};
var YJ={Xh:"DeleteLicenseAfterUse",Yh:"LicenseServer",Jm:"GetChallenge",Km:"HttpHeader",Om:"UserAgent",Fm:"Cookie",Wh:"CustomData"};_.r=$J.prototype;_.r.initialize=function(){this.a.on(TK,this.sg,this);this.a.on(eL,this.rg,this);this.a.on(fL,this.qg,this);this.a.on(UK,this.uh,this);this.a.on(WK,this.th,this);this.a.on(gL,this.tg,this)};_.r.release=function(){bK(this,_.Ho);this.l=!1;this.o=-1;this.h=2};_.r.destroy=function(){this.release();this.a.off(TK,this.sg);this.a.off(eL,this.rg);this.a.off(fL,this.qg);this.a.off(UK,this.uh);this.a.off(WK,this.th);this.a.off(gL,this.tg);this.m=this.a=null};
_.r.sg=function(){this.g.debug("Buffering start. Player state: ",this.a.getState());this.h=this.a.B?1:2;bK(this,_.Mo)};_.r.rg=function(a){this.g.debug("Buffering progress: "+a.percent+" %. Player state: ",aK(this.f))};_.r.qg=function(){this.g.debug("Buffering complete. Player state: ",this.a.getState());if(!this.l){this.l=!0;var a=this.m.getConfiguration().autoplay,b=this.a.getState()===hL;if(!a&&b){bK(this,_.Uo);return}}if(a=this.f!==_.To)a=this.a.getState(),a=a===cK||a===dK;a&&eK(this)};
_.r.uh=function(){this.g.debug("Preparing starts. AVPlay State: ",this.a.getState());this.a.getState()===iL?bK(this,_.To):this.g.error("AVPlay prepares while state is not IDLE")};_.r.th=function(){this.g.debug("Preparing ends: AVPlay state:",this.a.getState())};_.r.tg=function(){bK(this,_.Oo)};_.r.getState=function(){return this.f};_.r=fK.prototype;_.r.initialize=function(a){this.m=a};
_.r.load=function(a){var b=this,c,d,e,f,g,h,l;return _.E(function(m){switch(m.a){case 1:if(!b.m)return b.g.debug("Text streamer is not initialized. Will not load()"),m["return"]();b.B=a;c=b;return _.x(m,hK(b),2);case 2:c.j=m.f;if(!b.j)return b.g.debug("Could not find manifest parser for source. Make sure parsers are registered."),m["return"]();d={networkingEngine:b.m.getNetworkEngine(),filterNewPeriod:function(){},filterAllPeriods:function(){},onTimelineCueAdded:function(){},onEvent:function(){},
onError:function(){}};_.A(m,3);e=b;return _.x(m,b.j.start(a.url,d),5);case 5:e.a=m.f;_.ah(m,4);break;case 3:return f=_.C(m),b.g.warn(f),_.A(m,6),g=b,_.x(m,b.j.start(a.url.replace("https://","http://"),d),8);case 8:g.a=m.f;_.ah(m,4);break;case 6:h=_.C(m),b.g.error(h),b.a=null;case 4:if(!b.a||!gK(b.a)){m.F(0);break}b.h=iK(b);_.A(m,10);return _.x(m,b.h.I,12);case 12:b.f=jK(b);l=b.m.getConfiguration();b.f.h=l.streaming;b.o=l.preferredTextLanguage;b.A=l.preferredTextRole;b.C=l.preferForcedSubtitles;_.ah(m,
0);break;case 10:_.C(m),b.g.debug("Could not setup media source..."),b.h=null,b.f=null,b.j=null,b.a=null,_.y(m)}})};_.r.tj=function(a){this.g.debug(_.iz,a);this.w=!0;var b=_.uB(a.textStreams,this.o||"",this.A||"",this.C)[0]||null;this.l&&(a.textStreams.includes(this.l)&&(b=this.l),this.l=null);return{variant:null,text:b}};_.r.sj=function(){this.g.debug("canSwitch_");this.w=!1;this.l&&(_.cD(this.f,this.l,!0,0),this.l=null)};_.r.U=function(){this.g.debug("onError_")};
_.r.uj=function(){this.j&&this.j.update&&this.j.update()};_.r.start=function(){var a=this;return _.E(function(b){if(!a.f)return b["return"]();try{a.f.start()}catch(c){a.g.error("Error while starting streaming engine",c)}_.y(b)})};_.r.setTextVisibility=function(a){this.g.debug("Set text visibility",a);this.h&&this.h.getTextDisplayer().setTextVisibility(a)};_.r.release=function(){var a=this;return _.E(function(b){a.m=null;a.a=null;a.B=null;a.A=null;a.o=null;a.w=!0;a.l=null;_.y(b)})};
_.r.destroy=function(){var a=this;return _.E(function(b){switch(b.a){case 1:if(!a.j){b.F(2);break}return _.x(b,a.j.stop(),3);case 3:a.j=null;case 2:if(!a.f){b.F(4);break}return _.x(b,a.f.destroy(),5);case 5:a.f=null,a.w=!0;case 4:if(!a.h){b.F(0);break}return _.x(b,a.h.destroy(),7);case 7:a.h=null,_.y(b)}})};_.w(oK,_.U);_.r=oK.prototype;_.r.jh=function(a){var b=a.eventid;a=a.data;switch(b){case jL:0<Object.keys(this.f).length||(this.g.debug("Loading track manager!"),this.load());b=webapis.avplay.getCurrentStreamInfo();0<b.length&&(b=+zK(this,b[0].extra_info).Bit_rate,b=DK(this,{bandwidth:b}))&&(this.w=b,pK(this,b));break;case kL:qK(this);break;default:this.g.debug("Event type: "+b+" data: "+a)}};_.r.zf=function(a){a.detail.currentState===_.Vo&&this.m.off(_.Tf,this.zf)};
_.r.initialize=function(a){var b=this;this.m=a;this.a=this.m.a;this.m.on(_.Tf,function(c){b.A||(c=c.detail,c.currentState===_.Vo&&(b.g.debug("Current state",c.currentState),b.A=!0,rK(b)))});this.a.on(lL,this.jh,this)};_.r.release=function(){this.f={};this.h=this.w=this.l=this.j=null;this.A=!1;this.o=1};
_.r.load=function(){if(this.a&&!(0<Object.keys(this.f).length)){this.h=this.m.h;this.m.off(_.Tf,this.zf);this.m.on(_.Tf,this.zf,this);try{var a=PK(this.a);this.f=CK(this,a);var b=this.f[_.T]||[];b.length&&(this.j=b[0].renditions[0]||null);qK(this)}catch(c){this.g.debug("Could not load track manager")}}};_.r.destroy=function(){this.a.off(lL,this.jh);this.a=this.m=null};_.r.getVideoTracks=function(){return this.f[_.Qj]||[]};_.r.getAudioTracks=function(){return this.f[_.T]||[]};
_.r.fa=function(){return this.f[_.S]||[]};_.r.ka=function(){return GK(this,_.Qj)};_.r.Qa=function(){return GK(this,_.T)};_.r.Ha=function(){return GK(this,_.S)};_.r.bb=function(){return this.w};_.r.mb=function(){this.g.info(NJ);return null};_.r.nb=function(){this.g.info(NJ);return null};_.r.Ia=function(){var a=this.ka();return a?a.track:null};_.r.ja=function(){var a=this.Qa();return a?a.track:null};_.r.ua=function(){var a=this.Ha();return a?a.track:null};
_.r.ib=function(a){var b=this;null===a?(a=this.ka(),ZK(this.a,a.bandwidth,null).then(function(){qK(b)})):0<a.renditions.length&&this.Ya(a.renditions[0])};_.r.za=function(a){a?vK(this,a.renditions[0]):this.g.warn("Cannot disable audio tracks on this platform.","Consider muting audio instead...")};_.r.La=function(a){a?(a=a.renditions[0],this.h?nK(this.h,a.track):vK(this,a)):(this.g.debug("Disabling text tracks"),this.l=null,$K(this.a,!1),this.m.trigger(new _.L(_.nl)))};
_.r.Ya=function(a){var b=this,c=this.ka();this.a.o||a.width!==c.width||a.height!==c.height||a.bandwidth!==c.bandwidth?(this.w=a,pK(this,a),ZK(this.a,c.bandwidth,a.bandwidth).then(function(){qK(b)})["catch"](function(d){var e=new _.P(_.Q,7,7200,{tizenerror:d});b.g.debug("Error while switching video track",d);b.m.onError(e)})):this.g.debug("Trying to switch to already active rendition. Doing nothing...")};_.r.gb=function(a){vK(this,a)};_.r.hb=function(a){this.h?nK(this.h,a.track):vK(this,a)};
_.r.addTextTrack=function(){};_.r.ma=function(){return this.a.o};oK.prototype.isAbrEnabled=oK.prototype.ma;oK.prototype.addTextTrack=oK.prototype.addTextTrack;oK.prototype.setTextRendition=oK.prototype.hb;oK.prototype.setAudioRendition=oK.prototype.gb;oK.prototype.setVideoRendition=oK.prototype.Ya;oK.prototype.setTextTrack=oK.prototype.La;oK.prototype.setAudioTrack=oK.prototype.za;oK.prototype.setVideoTrack=oK.prototype.ib;oK.prototype.getTextTrack=oK.prototype.ua;oK.prototype.getAudioTrack=oK.prototype.ja;
oK.prototype.getVideoTrack=oK.prototype.Ia;oK.prototype.getLoadingTextRendition=oK.prototype.nb;oK.prototype.getLoadingAudioRendition=oK.prototype.mb;oK.prototype.getLoadingVideoRendition=oK.prototype.bb;oK.prototype.getTextRendition=oK.prototype.Ha;oK.prototype.getAudioRendition=oK.prototype.Qa;oK.prototype.getVideoRendition=oK.prototype.ka;oK.prototype.getTextTracks=oK.prototype.fa;oK.prototype.getAudioTracks=oK.prototype.getAudioTracks;oK.prototype.getVideoTracks=oK.prototype.getVideoTracks;_.w(HK,_.tl);_.r=HK.prototype;_.r.nj=function(){this.w=!0;this.f||this.trigger(new _.L(TK))};_.r.mj=function(a){this.w=!0;this.trigger(new _.L(eL,{percent:a}))};_.r.lj=function(){this.w=!1;this.trigger(new _.L(fL))};_.r.qj=function(){this.trigger(new _.L(gL))};_.r.pj=function(a,b){this.trigger(new _.L(lL,{eventid:a,data:b}))};_.r.rj=function(a,b,c,d,e){this.trigger(new _.L(mL,{duration:a,text:b,subtitleType:c,attriCount:d,attributes:e}))};
_.r.oj=function(a,b){this.trigger(new _.L(nL,{drmType:a,drmData:b}));if(this.h){var c=this.h;if(c.j)if(c.a===_.Rd&&"Challenge"===b.name)ZJ(c,b);else if("DrmError"===b.name){c.g.debug("DrmError event",b);var d=new _.P(_.Q,6,6005,{message:JSON.stringify(b)});c.D.onError(d)}}};_.r.U=function(a){this.trigger(new _.L(oL,{eventType:a}))};
_.r.play=function(){function a(){return new Promise(function(d,e){function f(){d();clearTimeout(g)}var g=null;b.one(JK,f,b);g=setTimeout(function(){b.off(JK,f);e("Timeout")},3E4)})}var b=this,c=this.getState();if(c===iL)return(new Promise(function(d,e){webapis.avplay.prepareAsync(function(){LK(b);d(webapis.avplay.play())},function(f){b.trigger(new _.L(oL));e(f)})})).then(function(){return a()});if(c===dK||c===hL)try{return webapis.avplay.play(),a()}catch(d){return Promise.reject(d)}return c===cK?
Promise.resolve():Promise.reject("Player is in invalid state")};_.r.pause=function(){try{webapis.avplay.pause()}catch(a){Promise.reject(a)}return this.getState()===dK?Promise.resolve():Promise.reject()};
_.r.setPlaybackRate=function(a){var b=this.getState();if(b===hL||b===cK||b===dK){try{webapis.avplay.setSpeed(a),this.C=a}catch(c){return this.g.debug("Error while trying to set playback rate",c),this.setPlaybackRate(this.C)}return!0}this.g.debug("Cannot set playback rate; AVPlay is in inconsistent state: "+b);return!1};_.r.getPlaybackRate=function(){return this.C};
_.r.load=function(a,b){var c=this,d;return _.E(function(e){switch(e.a){case 1:return c.g.debug("configure()",b||""),_.A(e,2),_.x(e,SK(c),4);case 4:return _.x(e,YK(c,a,b),5);case 5:_.ah(e,0);break;case 2:throw d=_.C(e),new _.P(_.Q,7,7003,null,d);}})};_.r.getState=function(){if(this.f&&this.a)return this.a.eg;try{return webapis.avplay.getState()}catch(a){this.U(JSON.stringify(a))}};
_.r.seek=function(a){var b=this,c=1E3*a;return new Promise(function(d,e){b.B=!0;b.m.trigger(new _.L(_.og));webapis.avplay.seekTo(c,function(){b.B=!1;b.m.trigger(new _.L(_.mg));d()},function(){b.B=!1;e()})})};_.r.getPosition=function(){if(this.f&&this.a)return this.a.position;try{return webapis.avplay.getCurrentTime()/1E3}catch(a){this.U(JSON.stringify(a))}};_.r.getDuration=function(){if(this.f&&this.a)return this.a.duration;try{return webapis.avplay.getDuration()/1E3}catch(a){this.U(JSON.stringify(a))}};
_.r.release=function(){var a=this;return new Promise(function(b,c){try{a.h&&(a.h.release(),a.h=null);webapis.avplay.stop();webapis.avplay.close();for(var d in a.j){var e=a.j[d];e&&e.Be.stop()}a.j={};a.C=1;a.B=!1;a.l=null;a.a=null;return b()}catch(f){return c(f)}})};_.r.getVolume=function(){var a=null;try{a=tizen.tvaudiocontrol.getVolume()}catch(b){switch(b.name){case PJ:this.g.debug("The application does not have the privilege to get the volume.",QJ);break;default:this.g.debug(MJ,b)}}return a};
_.r.setVolume=function(a){try{tizen.tvaudiocontrol.setVolume(Math.max(0,Math.min(100*a,100)))}catch(b){switch(b.name){case "InvalidValueError":this.g.warn("Invalid value passed for setVolume.","The passed value value should be in the range of 0 to 1.");break;case PJ:this.g.warn("The application does not have the privilege to set the volume.",QJ);break;default:this.g.warn("An unknown error occurred while trying to set volume",b)}}};
_.r.isLive=function(){if(this.f&&this.a)return this.a.isLive;try{return"1"===webapis.avplay.getStreamingProperty("IS_LIVE")}catch(a){this.U(JSON.stringify(a))}};_.r.stop=function(){try{webapis.avplay.stop()}catch(a){this.g.debug(a)}};_.r.getDrmInfo=function(){this.h&&this.h.getDrmInfo();return null};_.r.setSourceIndex=function(a){this.G=a};_.r.getSourceIndex=function(){return this.G};_.r.getLoadedSource=function(){return this.l&&this.l[this.getSourceIndex()]};
var iL="IDLE",hL="READY",cK="PLAYING",dK="PAUSED",AK=_.kc,tK="AUDIO",uK="TEXT",kL="PLAYER_MSG_RESOLUTION_CHANGED",jL="PLAYER_MSG_BITRATE_CHANGE",XJ={PLAYREADY:"PLAYREADY",Gm:"EME_PLAYREADY",Pm:"VERIMATRIX",Vd:"WIDEVINE_CDM",Hm:"EME_WIDEVINE_CDM",Rm:"WIDEVINE_CLASSIC"};_.w(aL,_.tl);_.r=aL.prototype;_.r.og=function(){var a=this;this.g.debug("On Stream completed. Current time: ",this.getPosition());this.trigger(new _.L(_.me));this.configuration.loop?this.seek(this.configuration.startTime||0)["catch"](function(){a.g.debug("Could not loop playback")}):this.a.stop()};_.r.mg=function(a){this.trigger(new _.L(_.eg,{currentTime:a.currentTime/1E3}))};
_.r.pg=function(a){var b=this.a.getPosition(),c=b+a.duration/1E3,d=a.text||"";this.g.debug("Got subtitles: ",d,"start:",b,"end:",c,a);(d=_.R.Pf(d))&&this.o.append([new _.di(b,c,d)],[])};_.r.ng=function(a){this.g.debug("DRM event: "+a.drmType+", data: "+a.drmData)};_.r.lh=function(){this.A||(this.g.debug("Initial buffering completed..."),this.A=!0)};
_.r.U=function(a){this.g.debug("Error: TYPE: "+a.eventType);bK(this.f,_.So);a=new _.P(_.Q,7,7200,{tizenerror:a.eventType});this.a.release();this.trigger(new _.L(_.ne,{detail:a}))};
_.r.init=function(a,b){this.configuration=this.B=b;this.w=a;this.a.on(gL,this.og,this);this.a.on(JK,this.mg,this);this.a.on(mL,this.pg,this);this.a.on(nL,this.ng,this);this.a.on(oL,this.U,this);this.a.on(fL,this.lh,this);this.f.initialize();this.l.initialize(this);this.g.debug("Initializing player surface");this.w.hideMediaElement();var c=pL;pL+=1;this.j=_.qp(_.Te,{id:"__clpp_tizen_player_"+c,type:"application/avplayer"});this.w.addElementToContainer(this.j,!0);var d=this.w.getMedia();if(d){c=this.j;
var e=[_.Hg,_.re,"position",_.ye,"top"],f={};d=null!==d.parentElement?window.getComputedStyle(d,null):d.style;if(!e||0===e.length){e||(e=[]);for(var g in d)e.push(g)}g=_.u(e);for(e=g.next();!e.done;e=g.next())e=e.value,f[e]=d[e];_.sp(c,f);bL(this)}};_.r.getSurface=function(){return this.w};_.r.getConfiguration=function(){return this.configuration};
_.r.destroy=function(){var a=this;return _.E(function(b){switch(b.a){case 1:return _.x(b,a.release(),2);case 2:a.a.off(gL,a.og);a.a.off(JK,a.mg);a.a.off(mL,a.pg);a.a.off(nL,a.ng);a.a.off(oL,a.U);a.a.off(fL,a.lh);if(!a.h){b.F(3);break}return _.x(b,a.h.destroy(),4);case 4:a.h=null;case 3:a.j&&(a.j.parentElement.removeChild(a.j),a.j=null),a.l.destroy(),a.f.destroy(),a.l=null,a.f=null,_.y(b)}})};_.r.namespace=function(){return qL};_.r.getPlaybackRate=function(){return this.a.getPlaybackRate()};
_.r.setDrmCustomDataModifier=function(){};_.r.setCdnErrorCallback=function(){};_.r.detach=function(){};_.r.setPlaybackRate=function(a){this.a.setPlaybackRate(a)};_.r.getPosition=function(){return 0<(this.configuration.startTime||0)&&!this.A?0:this.f.getState()===_.Oo?this.getDuration():this.a.getPosition()||0};_.r.seek=function(a){return typeof a===_.k&&0<=a?(this.isLive()||(a=Math.min(a,this.getDuration())),this.a.seek(a)):Promise.reject()};_.r.getPresentationStartTime=function(){return null};
_.r.getSeekRange=function(){return{start:0,end:0}};_.r.getVolume=function(){var a=this.a.getVolume();return typeof a===_.k?a/100:null};_.r.setVolume=function(a){this.a.setVolume(a)};_.r.getDuration=function(){return this.a.getDuration()};_.r.getBufferInfo=function(){this.g.warn(_.va);return new _.sl};_.r.getTrackManager=function(){return this.l};_.r.unload=function(){var a=this;return this.a.release().then(function(){a.l.release()})};
_.r.release=function(){var a=this;return _.E(function(b){switch(b.a){case 1:if(!a.h){b.F(2);break}return _.x(b,a.h.release(),2);case 2:if(!a.o){b.F(4);break}return _.x(b,a.o.destroy(),5);case 5:a.o=null;case 4:return _.x(b,a.a.release(),6);case 6:a.l.release(),a.f.release(),a.A=!1,_.y(b)}})};
_.r.load=function(a){var b=this,c,d,e,f,g;return _.E(function(h){switch(h.a){case 1:_.Cl(a)&&(b.configuration=_.Bl(b.B,a));c=_.vo(b.configuration,[_.te,"native"]);b.o=c.create(b);d=_.Zo(b.configuration)[0];e=!!b.configuration.tizen&&b.configuration.tizen.sideStreamText;if(!e){h.F(2);break}b.h=new fK;b.h.initialize(b);_.A(h,3);return _.x(h,b.h.load(d),5);case 5:b.h.start();_.ah(h,2);break;case 3:f=_.C(h),b.g.error(f);case 2:return _.A(h,6),_.x(h,b.a.load(b.configuration),8);case 8:_.ah(h,7);break;
case 6:throw g=_.C(h),b.onError(g),g;case 7:b.l.load(),_.y(h)}})};_.r.play=function(){var a=this;this.trigger(new _.L(_.gf));bL(this);return this.a.play().then(function(){eK(a.f)})};_.r.pause=function(){var a=this;return this.a.pause().then(function(){eK(a.f)})};_.r.getState=function(){return this.f.getState()};_.r.getPeriods=function(){return[]};_.r.onError=function(a){var b=new _.L(_.ne,{detail:a});a.severity===_.Q&&(bK(this.f,_.So),this.a.release());this.trigger(b);b.defaultPrevented&&(b.a=!0)};
_.r.getDrmInfo=function(){return this.a.getDrmInfo()};_.r.isEnded=function(){return this.f.getState()===_.Oo};_.r.isPaused=function(){return this.a.getState()===dK};_.r.isMuted=function(){return OK(this.a)};_.r.setMuted=function(a){XK(this.a,a)};_.r.getNetworkEngine=function(){return this.C};_.r.setNetworkEngine=function(a){this.C=a};_.r.isLive=function(){return this.a.isLive()};_.r.getStats=function(){return null};_.r.setSourceIndex=function(a){this.a.setSourceIndex(a)};_.r.getSourceIndex=function(){return this.a.getSourceIndex()};
_.r.getLoadedSource=function(){return this.a.getLoadedSource()};_.r.canPlay=function(a,b){return(new cL).canPlay(a,b)};_.r.getTimelineCues=function(){return[]};_.r.getTextDisplayer=function(){return this.o};_.r.resetAbr=function(){};aL.prototype.getTextDisplayer=aL.prototype.getTextDisplayer;aL.prototype.setNetworkEngine=aL.prototype.setNetworkEngine;aL.prototype.getNetworkEngine=aL.prototype.getNetworkEngine;var qL="clpp.tizen",pL=0;cL.prototype.a=function(){return qL};
cL.prototype.canPlay=function(a){a=a.type;var b=!!window.webapis;if((a===_.Tc||a===_.dl||a===_.Yc)&&b){if(_.Dj(2))return 2;if(_.Dj(3)||_.Dj(4)||_.Dj(5)||_.Dj(6))return _.J("Use of clpp.tizen.TizenComponent is not recommended for Tizen version \x3e\x3d 3."),1}return 0};cL.prototype.create=function(){return new aL};_.w(dL,_.Ir);dL.prototype.f=function(){_.zh(new cL)};dL.prototype.a=function(){var a=qL;a&&_.xh[a]&&(delete _.xh[a],_.yh.info("Removed Player factory: '"+a+"'"))};dL.prototype.id=function(){return"tizen"};_.H("clpp.tizen.TizenComponent",dL);var TK="onbufferingstart",eL="onbufferingprogress",fL="onbufferingcomplete",gL="onstreamcompleted",JK="oncurrentplaytime",lL="onevent",mL="onsubtitlechange",nL="ondrmevent",oL="onerror",UK="preparingstart",WK="preparingend";};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();