(function(){var g={}; var _ = _ || {}
var f=function(window){var wv="Registering listeners",xv="clpp.vimond.VimondPlugin",yv=function(a,b,c,d,e){this.G=a;this.H=b;this.I=c;this.m=d;this.C=e;this.a=new _.Eh;this.l=!0;this.f=this.j=this.A=!1;this.B=null;this.h=new _.uk(this.Dg.bind(this));this.g=new _.K("clpp.vimond.VimondDispatcher");this.o=this.w=0;this.m&&this.a&&(this.g.debug(wv),this.a.on(this.m,_.Tf,this.zj.bind(this)),this.a.on(this.m,_.eg,this.Aj.bind(this)),this.a.on(this.m,_.uc,this.xj.bind(this)),this.a.on(this.m,_.vc,this.yj.bind(this)))},zv=function(a,
b){a.m.trigger(new _.L(_.xg,{detail:b}))},Av=function(a,b,c){b&&(a.A=!0,a.h.stop());a.m.onError(new _.P(b?_.Q:1,9,9201,c))},Bv=function(a,b,c,d,e){this.l=a;this.o=c;this.h=b;this.a=d;this.j=e;this.g=new _.K("clpp.vimond.VimondService");this.f=0},Cv=function(a){this.m=a;this.a=new _.Eh;this.g=new _.K("clpp.vimond.VimondAdapter");this.f=this.h=!1;this.m&&this.a&&(this.g.debug(wv),this.a.on(this.m,_.Gf,this.wl.bind(this)),this.a.on(this.m,_.uc,this.vj.bind(this)),this.a.on(this.m,_.vc,this.wj.bind(this)))},
Dv=function(a,b){var c=a.m.getState();if(1===b)return["str-start",_.of];if(a.h)return[_.le,_.cf];if(c===_.Oo)return[_.le,null];if(c===_.So)return[_.ne,_.cf];var d=_.cf;if(c===_.Mo||c===_.Vo||a.f)d=_.of;return["period",d]},Ev=function(){this.a=!1;this.g=new _.K(xv);this.j=this.h=this.f=null},Fv=function(){};_.r=yv.prototype;_.r.Aj=function(){this.f||(this.f=1<Math.abs(this.w-this.m.getPosition()));this.w=this.m.getPosition()};_.r.xj=function(){this.g.debug("Ad break started");this.j=!0};
_.r.yj=function(){this.g.debug("Ad break stopped");this.j=!1};
_.r.zj=function(a){var b=this,c,d,e,f,g;return _.E(function(h){if(1==h.a){c=a.detail;d=_.Qo;e=c.currentState;f=c.previousState;b.g.debug("State changed, prev: "+f+" curr: "+e);if(b.A||b.j)return h["return"]();if(e===b.B&&!b.f)return b.g.debug("Ignore transition"),h["return"]();if(b.l&&e!==d.PLAYING)return h["return"]();if(b.f&&[d.PAUSED,d.BUFFERING].includes(e))return b.g.debug("Seeking"),h["return"]();b.f&&e===d.PLAYING&&(b.g.debug("Seeked"),b.f=!1);g=[d.PLAYING,d.PAUSED,d.ERROR,d.ENDED];if(!g.includes(e))return h.F(0);
b.B=e;return _.x(h,b.Dg(),3)}e===d.ENDED&&b.h.stop();_.y(h)})};
_.r.Dg=function(){var a=this,b,c,d,e,f,g;return _.E(function(h){if(1==h.a){var l=Math.floor(Date.now()/1E3);0<a.o&&a.g.debug("Last event was "+(l-a.o)+" seconds ago");a.o=l;a.h.stop();a.h.aa(a.l?10:a.G);a.l=!1;_.A(h,2);l=a.C;l.f++;var m=_.N.oa(l.o);m.client.buildName=_.wa;m.client.buildVersion=_.ja;var n=m.client,p=l.a.m.getDrmInfo();n.drm=p?p.keySystem:"";m.client.pageUrl=document.location.href;m.client.streamUrl=l.a.m.getLoadedSource().url;m.client.userAgent=navigator.userAgent;m.client.videoFormat=
l.a.m.getLoadedSource().type||"";n=m.client;p=l.a.m.getLoadedSource();p=((new _.Xj(p.url)).scheme||"").replace(":","");n.videoProtocol=p;n=Dv(l.a,l.f);m.client.playerEvent=n[0]||"";m.client.playerState=n[1]||"";m.progress.vod&&(m.progress.vod.position=l.a.getPosition());if(n=m.progress.live){p=l.a;var q=p.m.getPresentationStartTime()||0;p=Math.floor(q+p.m.getPosition());p=(new Date(1E3*p)).toISOString();n.position=p;q=l.a;p=q.m.getPosition();q=q.m.getSeekRange().end;n.onLiveEdge=30>Math.abs(q-p);
typeof n.liveResumePossible!==_.hd&&(n.liveResumePossible=!0)}m.progress.eventNumber=l.f;m.timestamp=(new Date).toISOString();l.g.debug("Fire an event");n=_.rj(l.l);n.method="POST";n.contentType="application/json";n.headers.Authorization="Bearer "+l.h;n.body=_.R.ed(JSON.stringify(m));l=l.j.fetch(n).O;return _.x(h,l,4)}if(2!=h.a)return b=h.f,zv(a,b),_.ah(h,0);d=c=_.C(h);e=d.code;f=d.data;g=[1002,1003];g.includes(e)?(a.g.debug("Unreachable service"),zv(a,f),Av(a,a.H,f)):1001===e?(a.g.debug("Generic service error"),
zv(a,f),Av(a,a.I,f)):a.g.error(c.toString());_.y(h)})};_.r.dispose=function(){this.g.debug(_.gc);_.Hh(this.a);this.h.stop()};Bv.prototype.Vf=function(a){this.h=a};_.r=Cv.prototype;_.r.getPosition=function(){return Math.floor(this.m.getPosition())};_.r.wl=function(){this.h=!0};_.r.vj=function(){this.f=!0};_.r.wj=function(){this.f=!1};_.r.dispose=function(){this.g.debug(_.gc);_.Hh(this.a)};_.w(Ev,_.rt);_.r=Ev.prototype;_.r.onPlayerCreated=function(){};
_.r.onContentWillLoad=function(a){var b=a.getConfiguration();(this.a=!_.N.R(b.vimond)&&typeof b.vimond===_.Te)?a.namespace()===_.Cd&&(this.a=!1,this.g.info("Vimond does not report when casting.")):this.g.warn("Vimond plugin is loaded but not configured. Will do nothing.");if(this.a){b=a.getConfiguration().vimond;for(var c=_.u(["authToken","playerEventRequest"]),d=c.next();!d.done;d=c.next())if(d=d.value,!b[d]){this.g.warn(d+" key is missing");a.onError(new _.P(1,9,9200));return}this.g.debug("Configuration is valid");
c=b.failIfUnreachable;typeof c!==_.hd&&(c=!0);d=b.failOnError;typeof d!==_.hd&&(d=!0);this.f=new Cv(a);this.h=new Bv(b.playerEventRequest.uri,b.authToken,b.playerEventRequest.body,this.f,a.getNetworkEngine());this.j=new yv(b.playerEventRequest.eventInterval,c,d,a,this.h)}};_.r.onPlayerWillRelease=function(){this.a&&(this.f&&this.f.dispose(),this.j&&this.j.dispose(),this.j=this.h=this.f=null)};_.r.onPlayerWillDestroy=function(){};_.r.id=function(){return"vimond"};
_.r.Vf=function(a){this.a&&this.h&&this.h.Vf(a)};_.H(xv,Ev);Ev.prototype.updateAuthToken=Ev.prototype.Vf;Ev.Id="vimond";Fv.prototype.create=function(){return new Ev};_.nq(new Fv);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();