(function(){var g={}; var _ = _ || {}
var f=function(window){var Hu=" The setting will be ignored.",Iu="VTT parser encountered an invalid VTT setting: ",Ju="application/x-subrip",Ku="text/srt",Lu='text/vtt; codecs\x3d"vtt"',Mu='text/vtt; codecs\x3d"wvtt"',Nu=function(a){_.lj(a,/[ \t]+/gm)},Ou=function(a){return a.a==a.f.length?null:(a=_.lj(a,/[^ \t\n]*/gm))?a[0]:null},Pu=function(){},Qu=function(a){var b="";for(a=a.split(/\n/);3<a.length;){for(var c=3;c<a.length;++c)a[2]+="\n"+a[c];a.splice(3,a.length-3)}if(3!==a.length)return"";c=0;!a[0].match(/\d+:\d+:\d+/)&&
a[1].match(/\d+:\d+:\d+/)&&(b+=a[0].match(/\w+/)+"\n",++c);if(a[c].match(/\d+:\d+:\d+/)){var d=a[1].match(/(\d+):(\d+):(\d+)(?:,(\d+))?\s*--?>\s*(\d+):(\d+):(\d+)(?:,(\d+))?/);if(d)b+=d[1]+":"+d[2]+":"+d[3]+"."+d[4]+" --\x3e ",b+=d[5]+":"+d[6]+":"+d[7]+"."+d[8]+"\n",++c;else return""}else return"";a[c]&&(b+=a[c]+"\n\n");return b},Ru=function(){},Su=function(a){this.a=a},Uu=function(a,b,c){var d;if(d=/^align:(start|middle|center|end|left|right)$/.exec(b))b=d[1],"middle"==b?a.textAlign=_.Zh:a.textAlign=
_.Nt[b.toUpperCase()];else if(d=/^vertical:(lr|rl)$/.exec(b))a.writingMode="lr"==d[1]?_.qg:_.rg;else if(d=/^size:([\d.]+)%$/.exec(b))a.size=Number(d[1]);else if(d=/^position:([\d.]+)%(?:,(line-left|line-right|center|start|end))?$/.exec(b))a.position=Number(d[1]),d[2]&&(b=d[2],a.positionAlign=b==_.Ce||b==_.Sf?_.Ce:b==_.De||b==_.le?_.De:_.sd);else if(d=/^region:(.*)$/.exec(b)){if(b=Tu(c,d[1]))a.region=b}else{a:{if(c=/^line:([\d.]+)%(?:,(start|end|center))?$/.exec(b))a.lineInterpretation=1,a.line=Number(c[1]),
c[2]&&(a.lineAlign=_.Ot[c[2].toUpperCase()]);else if(c=/^line:(-?\d+)(?:,(start|end|center))?$/.exec(b))a.lineInterpretation=_.ai,a.line=Number(c[1]),c[2]&&(a.lineAlign=_.Ot[c[2].toUpperCase()]);else{a=!1;break a}a=!0}return a}return!0},Tu=function(a,b){var c=a.filter(function(d){return d.id==b});return c.length?c[0]:(_.J("VTT parser could not find a region with id: ",b," The region will be ignored."),null)},Vu=function(a){a=_.lj(a,/(?:(\d{1,}):)?(\d{2}):(\d{2})\.(\d{2,3})/g);if(null==a)return null;
var b=Number(a[2]),c=Number(a[3]);return 59<b||59<c?null:Number(a[4])/1E3+c+60*b+3600*(Number(a[1])||0)},Wu=function(){Su.apply(this,arguments)},Xu=function(){this.a=null;this.g=new _.K("clpp.vtt.mp4")},Zu=function(a,b,c){var d,e,f;(new _.mm).L("payl",_.pm(function(g){d=_.R.Z(g)})).L("iden",_.pm(function(g){e=_.R.Z(g)})).L("sttg",_.pm(function(g){f=_.R.Z(g)})).parse(a);return d?Yu(d,e,f,b,c):null},Yu=function(a,b,c,d,e){a=new _.di(d,e,a,_.zg);b&&(a.id=b);if(c)for(b=new _.kj(c),c=Ou(b);c;)Uu(a,c,[])||
_.J(Iu,c,Hu),Nu(b),c=Ou(b);return a},$u=function(){this.j=new Ru};Pu.prototype.a=function(a){a=_.R.Z(a);a=a.replace(/\r+/g,"");a=a.replace(/^\s+|\s+$/g,"");a=a.replace(/<[a-zA-Z\\/][^>]*>/g,"");var b=a.split("\n\n");a="";if(0<b.length){a+="WEBVTT\n\n";b=_.u(b);for(var c=b.next();!c.done;c=b.next())a+=Qu(c.value)}return _.R.Va(a)};Ru.prototype.create=function(){return new Pu};Ru.prototype.probe=function(a,b){return(a===Ku||a===Ju)&&b===_.cg};Su.prototype.parseInit=function(){};
Su.prototype.parseMedia=function(a,b){var c=_.R.Z(a);c=c.replace(/\r\n|\r(?=[^\n]|$)/gm,"\n");var d=c.split(/\n{2,}/m);if(!/^WEBVTT($|[ \t\n])/m.test(d[0]))throw new _.P(_.Q,2,2E3);c=b.periodStart;if(d[0].includes("X-TIMESTAMP-MAP")){var e=d[0].match(/LOCAL:((?:(\d{1,}):)?(\d{2}):(\d{2})\.(\d{3}))/m),f=d[0].match(/MPEGTS:(\d+)/m);if(e&&f){c=Vu(new _.kj(e[1]));if(null==c)throw new _.P(_.Q,2,2E3);f=Number(f[1]);for(e=b.segmentStart;95443.7176888889<=e;)e-=95443.7176888889,f+=8589934592;c=b.periodStart+
f/9E4-c}}else this.a.streaming.relativeTextTimestamp&&null!==b.segmentStart&&(c=b.segmentStart);f=[];e=_.u(d);for(var g=e.next();!g.done;g=e.next()){var h=g.value;if(/^region/.test(h.toLowerCase())){h=new _.kj(h.replace(/\n/g," "));g=new _.gi;Ou(h);Nu(h);for(var l=Ou(h);l;){var m;a:{var n=g,p=l;if(m=/^id:(.*)$/.exec(p))n.id=m[1];else if(m=/^width:(\d{1,2}|100)%$/.exec(p))n.width=Number(m[1]);else if(m=/^lines:(\d+)$/.exec(p))n.height=Number(m[1]),n.heightUnits=2;else if(m=/^regionanchor:(\d{1,2}|100)%,(\d{1,2}|100)%$/.exec(p))n.regionAnchorX=
Number(m[1]),n.regionAnchorY=Number(m[2]);else if(m=/^viewportanchor:(\d{1,2}|100)%,(\d{1,2}|100)%$/.exec(p))n.viewportAnchorX=Number(m[1]),n.viewportAnchorY=Number(m[2]);else if(/^scroll:up$/.exec(p))n.scroll="up";else{m=!1;break a}m=!0}m||_.J("VTT parser encountered an invalid VTTRegion setting: ",l,Hu);Nu(h);l=Ou(h)}f.push(g)}}e=[];h=_.u(d);for(g=h.next();!g.done;g=h.next())if(g=g.value,/^style/.test(g.toLowerCase())){g=g.replace(/^style/i,"").replace(/\n/g," ");l=/[^{}]+{[^{}]*}/g;do(m=l.exec(g))&&
e.push(m[0]);while(m)}h=[];d=_.u(d);for(g=d.next();!g.done;g=d.next())if(g=g.value,g.includes("--\x3e")){p=g.split("\n");var q=c;if(1==p.length&&!p[0]||/^NOTE($|[ \t])/.test(p[0])||"STYLE"==p[0])g=null;else{g=null;p[0].includes("--\x3e")||(g=p[0],p.splice(0,1));l=new _.kj(p[0]);m=Vu(l);var t=_.lj(l,/[ \t]+--\x3e[ \t]+/g);n=Vu(l);if(null==m||null==t||null==n)throw new _.P(_.Q,2,2001);m+=q;n+=q;p=p.slice(1).join("\n").trim();m=new _.di(m,n,p,_.zg);g&&(m.id=g);Nu(l);for(n=Ou(l);n;)Uu(m,n,f)||_.J(Iu,
n,Hu),Nu(l),n=Ou(l);null!=g&&(m.id=g);g=m}g&&h.push(g)}return{cues:h,styles:e}};_.w(Wu,Su);Wu.prototype.parseMedia=function(a,b){return Su.prototype.parseMedia.call(this,(new Pu).a(a),b)};Xu.prototype.parseInit=function(a){var b=this,c=!1;(new _.mm).L(_.Oe,_.nm).L(_.fg,_.nm).L(_.Je,_.nm).Y("mdhd",function(d){0==d.version?(d.reader.skip(4),d.reader.skip(4),b.a=_.W(d.reader),d.reader.skip(4)):(d.reader.skip(8),d.reader.skip(8),b.a=_.W(d.reader),d.reader.skip(8));d.reader.skip(4)}).L(_.Ne,_.nm).L(_.Vf,_.nm).Y(_.Xf,_.om).L("wvtt",function(){c=!0}).parse(a);if(!this.a)throw new _.P(_.Q,2,2008);if(!c)throw new _.P(_.Q,2,2008);};
Xu.prototype.parseMedia=function(a,b){if(!this.a)throw this.g.error("No init segment for MP4+VTT!"),new _.P(_.Q,2,2008);var c=0,d=[],e,f=[],g=!1,h=!1,l=!1,m=null;(new _.mm).L("moof",_.nm).L("traf",_.nm).Y("tfdt",function(I){g=!0;c=0==I.version?_.W(I.reader):_.jm(I.reader)}).Y("tfhd",function(I){var O=I.flags;I=I.reader;I.skip(4);O&1&&I.skip(8);O&2&&I.skip(4);m=O&8?_.W(I):null}).Y("trun",function(I){h=!0;var O=I.version,M=I.flags;I=I.reader;var ba=_.W(I);M&1&&I.skip(4);M&4&&I.skip(4);for(var ha=[],
qa=0;qa<ba;qa++){var Ta={duration:null,sampleSize:null,Sf:null};M&256&&(Ta.duration=_.W(I));M&512&&(Ta.sampleSize=_.W(I));M&1024&&I.skip(4);M&2048&&(Ta.Sf=0==O?_.W(I):_.im(I));ha.push(Ta)}d=ha}).L(_.Ie,_.pm(function(I){l=!0;e=I})).parse(a);if(!l&&!g&&!h)throw new _.P(_.Q,2,2008);var n=c,p=new DataView(e.buffer,e.byteOffset,e.byteLength);p=new _.dm(p,!1);for(var q=_.u(d),t=q.next();!t.done;t=q.next()){t=t.value;var v=t.duration||m,z=t.Sf?c+t.Sf:n;n=z+(v||0);var D=0;do{var G=_.W(p);D+=G;var F=_.W(p);
F=_.rm(F);var B=null;"vttc"==F?8<G&&(B=_.lm(p,G-8)):("vtte"!=F&&this.g.error("Unknown box "+F+"! Skipping!"),p.skip(G-8));v?B&&f.push(Zu(B,b.periodStart+z/this.a,b.periodStart+n/this.a)):this.g.error("WVTT sample duration unknown, and no default found!")}while(t.sampleSize&&D<t.sampleSize)}return{cues:f.filter(_.ni),styles:[]}};_.w($u,_.Ir);$u.prototype.f=function(){_.ft[_.cg]=Su;_.ft[Lu]=Su;_.ft[Mu]=Su;_.ft[_.Wc]=Xu;_.ft[Ku]=Wu;_.ft[Ju]=Wu;_.ok.push(this.j)};$u.prototype.a=function(){_.gt(_.cg);_.gt(Lu);_.gt(Mu);_.gt(_.Wc);_.gt(Ku);_.gt(Ju);_.qk(this.j)};$u.prototype.id=function(){return"subtitles-vtt"};_.H("clpp.vtt.VttComponent",$u);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();