(function(){var g={}; var _ = _ || {}
var f=function(window){var wu='" event to Youbora',xu='Reporting "',yu="clpp.npaw.YouboraPlugin",zu="content.isLive",Au=function(a){return(a=a.getConfiguration().youbora)&&a.errorFilter?a.errorFilter:function(b){return{code:""+b.code,message:b.message,severity:b.severity}}},Bu=function(a,b,c,d){b=Au(b)(a);if(!b)return c.debug("Error not sent to Youbora",a.code,a.message),null;a=10003===a.code?"ad error":_.ne;b.severity===_.Q?(d.fireFatalError(b.code,b.message,b.metadata),c.debug('Reporting "fatal '+a+'" to Youbora',b.code,
b)):(d.fireError(b.code,b.message,b.metadata),c.debug(xu+a+'" to Youbora',b.code,b));return b},Cu=function(a){function b(c){var d=youbora.Adapter.call(this,c)||this;d.m=c;d.a=new _.Eh;d.g=new _.K("clpp.npaw.YouboraAdapter");d.w=!1;d.h=!1;d.registerListeners();d.B=!1;return d}_.w(b,youbora.Adapter);b.prototype.getPlayhead=function(){return this.getIsLive()?-1:this.m.getPosition()};b.prototype.getDuration=function(){return this.m.getDuration()};b.prototype.getRendition=function(){var c=this.m.getTrackManager();
if(c&&(c=c.ka())){var d=c.width;var e=c.height;var f=c.bandwidth}d&&e&&f||(c=this.l(),d=d||c.width,e=e||c.height,f=f||c.streamBandwidth);return youbora.Util.buildRenditionString(d,e,f)};b.prototype.getIsLive=function(){return this.m.isLive()};b.prototype.getResource=function(){var c=this.m.getLoadedSource();return c&&c.url};b.prototype.getBitrate=function(){return this.l().streamBandwidth};b.prototype.getThroughput=function(){return this.l().estimatedBandwidth};b.prototype.getPlayrate=function(){return this.m.getPlaybackRate()};
b.prototype.getFramesPerSecond=function(){var c=this.m.getTrackManager();return c&&(c=c.Ia())?c.frameRate:null};b.prototype.getPlayerName=function(){return _.wa};b.prototype.getVersion=function(){return"6.14.0-castlabsadapter-js"};b.prototype.getPlayerVersion=function(){return _.ja};b.prototype.registerListeners=function(){this.m&&this.a&&(this.g.debug("registering listeners"),youbora.Util.logAllEvents(this.m),this.a.on(this.m,_.Tf,this.K.bind(this)),this.a.on(this.m,_.ne,this.H.bind(this)),this.a.on(this.m,
_.og,this.J.bind(this)),this.a.on(this.m,_.mg,this.I.bind(this)),this.a.on(this.m,_.Nc,this.C.bind(this)),this.a.on(this.m,_.nd,this.G.bind(this)))};b.prototype.unregisterListeners=function(){this.g.debug(_.gc);_.Hh(this.a)};b.prototype.dispose=function(){youbora.Adapter.prototype.dispose.call(this);this.B=!0};b.prototype.l=function(){return this.m.getStats()||_.Do()};b.prototype.o=function(){return!!this.m.getConfiguration().autoplay};b.prototype.K=function(c){c=c.detail;this.j("state change",c);
if(c)switch(c.currentState){case _.To:this.o()&&this.f();break;case _.Vo:this.f();this.A();this.fireResume();this.fireBufferEnd();break;case _.Uo:this.o()&&this.f();this.A();this.fireBufferEnd();this.firePause();break;case _.Ho:this.fireBufferEnd();this.fireStop();break;case _.Oo:this.fireBufferEnd();this.w&&this.plugin.getAdsAdapter()?this.firePause():this.fireStop();break;case _.Mo:this.fireBufferBegin();break;default:this.g.debug("Unhandled state",c)}};b.prototype.f=function(){this.plugin.isInitiated||
(this.h=!1,this.fireInit())};b.prototype.A=function(){var c=this.m.getDrmInfo();c&&(c=c.keySystem,(c=c.startsWith(_.Rd)?"Widevine":c.startsWith(_.Md)?"FairPlay":c.match(/^com\.(microsoft|chromecast)\.playready/)?"PlayReady":c.startsWith(_.af)?"ClearKey":c.startsWith(_.Ld)?"Primetime":c)&&this.plugin.setOptions({"content.drm":c}));this.fireJoin()};b.prototype.H=function(c){!(c=c.detail)||this.h||10003===c.code&&this.plugin.getAdsAdapter()||(c=Bu(c,this.m,this.g,this))&&c.severity===_.Q&&(this.h=!0)};
b.prototype.J=function(){this.j(_.Mf);this.m.isEnded()||(this.f(),this.fireSeekBegin())};b.prototype.I=function(){this.j(_.Lf);this.fireSeekEnd()};b.prototype.C=function(c){this.g.debug("adsTimeline",c);c=c.adsTimeline;this.w=!!c&&c.pb()};b.prototype.G=function(c){this.g.debug("Casting",c);this.fireCasted()};b.prototype.j=function(c,d){for(var e=[],f=1;f<arguments.length;++f)e[f-1]=arguments[f];this.g.debug.apply(this.g,[xu+c+wu].concat(_.Og(e)))};return new b(a)},Du=function(a){function b(c){var d=
youbora.Adapter.call(this,c)||this;d.m=c;d.a=null;d.j=null;d.f=new _.Eh;d.g=new _.K("clpp.npaw.YouboraAdsAdapter");d.registerListeners();d.A=!1;d.l=!1;return d}_.w(b,youbora.Adapter);b.prototype.getDuration=function(){return this.a&&this.a.getDuration()};b.prototype.getRendition=function(){var c=null;this.a&&(c=youbora.Util.buildRenditionString(this.a.Bb(),this.a.Ab(),this.a.ob()));return c};b.prototype.getBitrate=function(){return this.a&&this.a.ob()};b.prototype.getPlayhead=function(){var c=this.m.getAdsManager();
return c&&c.getPosition()};b.prototype.getResource=function(){return this.a&&this.a.getMediaUrl()};b.prototype.getTitle=function(){return this.a&&this.a.getTitle()};b.prototype.getProvider=function(){return this.a&&this.a.getAdvertiserName()};b.prototype.getCreativeId=function(){return this.a&&this.a.getCreativeId()};b.prototype.getPosition=function(){var c=youbora.Constants.AdPosition,d=null;if(this.a)switch(this.a.cb()){case 0:d=c.Preroll;break;case 2:d=c.Postroll;break;case 1:d=c.Midroll}this.g.debug("Ad position",
d);return d};b.prototype.getIsSkippable=function(){return this.a&&-1!==this.a.getSkipTimeOffset()};b.prototype.getAudioEnabled=function(){var c=this.m.getAdsManager();return c&&0<c.getVolume()};b.prototype.getExpectedBreaks=function(){return this.j&&this.j.getCuePoints().length};b.prototype.getGivenBreaks=function(){return this.getExpectedBreaks()};b.prototype.getExpectedAds=function(){return this.a&&this.a.Db()};b.prototype.getGivenAds=function(){return this.getExpectedAds()};b.prototype.getBreaksTime=
function(){var c=this;return this.j&&this.j.getCuePoints().map(function(d){return-1===d?c.m.getDuration():d})};b.prototype.getIsFullscreen=function(){return this.m.getSurface().isFullscreen()};b.prototype.getIsVisible=function(){var c=this.m.getSurface().getContainer();c=youbora.Util.calculateAdViewability(c);this.g.debug("is container visible",c);return c};b.prototype.getPlayerName=function(){return _.wa};b.prototype.getVersion=function(){return"6.14.0-castlabsadsadapter-js"};b.prototype.getPlayerVersion=
function(){return _.ja};b.prototype.registerListeners=function(){this.m&&this.f&&(this.f.on(this.m,_.Nc,this.V.bind(this)),this.f.on(this.m,_.Hc,this.T.bind(this)),this.f.on(this.m,_.Dc,this.K.bind(this)),this.f.on(this.m,_.Fc,this.M.bind(this)),this.f.on(this.m,_.yc,this.I.bind(this)),this.f.on(this.m,_.zc,this.o.bind(this,1)),this.f.on(this.m,_.Cc,this.o.bind(this,2)),this.f.on(this.m,_.Jc,this.o.bind(this,3)),this.f.on(this.m,_.xc,this.H.bind(this)),this.f.on(this.m,_.Gc,this.P.bind(this)),this.f.on(this.m,
_.ne,this.J.bind(this)),this.f.on(this.m,_.uc,this.B.bind(this)),this.f.on(this.m,_.vc,this.C.bind(this)),this.f.on(this.m,_.wc,this.G.bind(this)),this.f.on(this.m,_.Ec,this.w.bind(this)))};b.prototype.unregisterListeners=function(){_.Hh(this.f)};b.prototype.dispose=function(){youbora.Adapter.prototype.dispose.call(this);this.A=!0};b.prototype.V=function(c){this.g.debug("ad timeline changed",c);this.j=c.adsTimeline};b.prototype.T=function(c){this.a=c.ad;this.h("ad start",this.a);this.fireStart();
this.fireJoin()};b.prototype.I=function(){this.h("ad ended");this.fireStop()};b.prototype.K=function(){this.h("ad pause");this.w();this.firePause()};b.prototype.M=function(){this.h("ad resume");this.w();this.fireResume()};b.prototype.G=function(){this.l=!0;this.h("ad buffering started");this.fireBufferBegin()};b.prototype.w=function(){this.l&&(this.h("ad buffering ended"),this.l=!1,this.fireBufferEnd())};b.prototype.o=function(c){this.h("ad quartile",c);this.fireQuartile(c)};b.prototype.H=function(){this.h("ad clicked");
var c=this.a&&this.a.Rb();this.g.debug("ad click through url: ",c);this.fireClick(c)};b.prototype.P=function(){this.h("ad skipped");this.fireSkip()};b.prototype.B=function(c){this.a=c.ad;this.h("ad break start",this.a);this.fireBreakStart()};b.prototype.C=function(){this.h("ad break stop");this.fireBreakStop();if(this.getPosition()===youbora.Constants.AdPosition.Postroll){var c=this.plugin.getAdapter();c&&c.fireStop()}};b.prototype.J=function(c){(c=c.detail)&&10003===c.code&&Bu(c,this.m,this.g,this)};
b.prototype.h=function(c,d){for(var e=[],f=1;f<arguments.length;++f)e[f-1]=arguments[f];this.g.debug.apply(this.g,[xu+c+wu].concat(_.Og(e)))};return new b(a)},Eu=function(){this.a=null;this.g=new _.K(yu);this.m=null},Fu=function(a,b){if(b.namespace()===_.Cd)return a.g.info("Youbora does not report when casting."),!1;var c=b.getConfiguration().youbora;if(!_.N.bh(c))return a.g.warn("Youbora plugin is loaded but not configured. Will do nothing."),!1;if(!c.accountCode)return a.g.warn("accountCode key is missing in Youbora config"),
b.onError(new _.P(1,9,9101)),!1;if(_.N.R(window.youbora))return a.g.warn("Youbora SDK not found."),b.onError(new _.P(1,9,9100)),!1;"6.8.49"!==youbora.VERSION&&(a.g.warn("Youbora SDK version is not supported. The supported version is 6.8.49, found version "+(youbora.VERSION+". Some or all features of YouboraPlugin may not work correctly.")),b.onError(new _.P(1,9,9102)));return!0},Gu=function(){};_.w(Eu,_.rt);_.r=Eu.prototype;_.r.Nf=function(a){this.a&&(this.a.removeAdsAdapter(),this.a.removeAdapter());if(this.a=a)this.a.setAdapter(Cu(this.m)),this.a.setAdsAdapter(Du(this.m))};_.r.getAdapter=function(){return this.a&&this.a.getAdapter()};_.r.getAdsAdapter=function(){return this.a&&this.a.getAdsAdapter()};_.r.onPlayerCreated=function(a){this.m=a;Fu(this,a)&&(a=a.getConfiguration().youbora,this.Nf(new youbora.Plugin(a)))};
_.r.onContentWillLoad=function(a,b){if(Fu(this,a)){var c=a.getConfiguration(),d=c.youbora;void 0===d[zu]&&(d[zu]=b.isLive);void 0===d["content.title"]&&(d["content.title"]=b.name);void 0===d.viewerId&&(d.viewerId=c.viewerId);this.a||this.Nf(new youbora.Plugin(d));this.a.setOptions(d)}};_.r.onPlayerWillRelease=function(){};_.r.onPlayerWillDestroy=function(){};_.r.id=function(){return"youbora"};_.H(yu,Eu);Eu.prototype.getAdsAdapter=Eu.prototype.getAdsAdapter;Eu.prototype.getAdapter=Eu.prototype.getAdapter;
Eu.prototype.setYouboraPlugin=Eu.prototype.Nf;Eu.Id="youbora";Gu.prototype.create=function(){return new Eu};_.nq(new Gu);};
if(typeof(module)!="undefined"&&module.exports){var x=require("./cl.core.js");_ = x._;(f.call(g,this));module.exports=g;}
else if (typeof(define)!="undefined"&&define.amd) {define(["./cl.core"], function(c){_=c._;(f.call(g,this));return g;});}
else{_=this.clpp._;(f.call(g,this));}
})();